### ISSUE TITLE
System cannot correctly create interfaces

### ISSUE THREAD

**Issue by tieguoevan** [Azure/SONiC#104]
Hi,

I built an image with newly code on branch master, but system boot with error, and some interfaces can't be created. See log below:

> Sep  4 11:12:05.0 sonic NOTICE orchagent: :- addHostIntfs: Create host interface for port Ethernet1
Sep  4 11:12:05.0 sonic NOTICE orchagent: :- doPortTask: Initialized port Ethernet1
Sep  4 11:12:05.0 sonic NOTICE orchagent: :- initializePort: Initializing port alias:Ethernet2 pid:1000000000021
Sep  4 11:12:05.0 sonic NOTICE orchagent: :- addHostIntfs: Create host interface for port Ethernet2
Sep  4 11:12:05.0 sonic NOTICE orchagent: :- doPortTask: Initialized port Ethernet2
Sep  4 11:12:05.0 sonic NOTICE orchagent: :- initializePort: Initializing port alias:Ethernet21 pid:100000000000c
Sep  4 11:12:05.0 sonic ERR syncd: :- checkReplyType: Expected to get redis type 2 got type 1, err: oid:0x1000000000001
Sep  4 11:12:05.0 sonic ERR syncd: :- guard: RedisReply catches system_error: command: *11#015#012$7#015#012EVALSHA#015#012$40#015#012320ab5885dadd4777f95f6f32453d48e8cc27209#015#012$1#015#0124#015#012$20#015#012ASIC_STATE_KEY_QUEUE#015#012$19#015#012ASIC_STATE_OP_QUEUE#015#012$22#015#012ASIC_STATE_VALUE_QUEUE#015#012$10#015#012ASIC_STATE#015#012$3#015#012128#015#012$2#015#012''#015#012$2#015#012''#015#012$2#015#012''#015#012, reason: Wrong expected type of result: Input/output error
Sep  4 11:12:05.0 sonic ERR syncd: :- main: Runtime error: Wrong expected type of result: Input/output error
Sep  4 11:12:05.0 sonic NOTICE syncd: :- exit_and_notify: sending switch_shutdown_request notification to OA
Sep  4 11:12:05.0 sonic NOTICE syncd: :- exit_and_notify: notification send successfull
Sep  4 11:12:05.0 sonic WARNING syncd: :- exit_and_notify: sleep forever to keep data plane active
Sep  4 11:12:05.0 sonic ERR syncd: :- hget: HGET failed, reply-type: 2, RIDTOVID: oid:0x100000000
Sep  4 11:12:05.0 sonic NOTICE orchagent: :- handle_switch_shutdown_request: switch shutdown request
Sep  4 11:12:05.0 sonic ERR orchagent: :- on_switch_shutdown_request: Syncd stopped
Sep  4 11:12:05.0 sonic INFO supervisord: orchagent terminate called without an active exception
Sep  4 11:12:05.229843 sonic INFO systemd[1]: Starting ifup for Ethernet30...
Sep  4 11:12:05.231747 sonic INFO systemd[1]: Started ifup for Ethernet30.
Sep  4 11:12:05.0 sonic INFO supervisord: syncd terminate called after throwing an instance of 'std::runtime_error
Sep  4 11:12:05.0 sonic INFO supervisord: syncd '
Sep  4 11:12:05.0 sonic INFO supervisord: syncd #015
Sep  4 11:12:05.0 sonic INFO supervisord: syncd   what():
Sep  4 11:12:05.0 sonic INFO supervisord: syncd HGET failed, unexpected reply type, memory exception#015

[orchagent.1504523525.64.core.gz](https://github.com/Azure/SONiC/files/1274639/orchagent.1504523525.64.core.gz)
[orchagent.1504523965.68.core.gz](https://github.com/Azure/SONiC/files/1274638/orchagent.1504523965.68.core.gz)
[orchagent.1504524078.69.core.gz](https://github.com/Azure/SONiC/files/1274640/orchagent.1504524078.69.core.gz)
[orchagent.1504524988.69.core.gz](https://github.com/Azure/SONiC/files/1274641/orchagent.1504524988.69.core.gz)

**Comment by stcheng** [comment]
thanks for raising this issue, it seems to be a race condition issue. we have just fixed this recently. could you also provide more information about the system/version you're running the SONiC upon?

https://github.com/Azure/sonic-sairedis/pull/218

**Comment by tieguoevan** [comment]
The platform we use is Broadcom Tomahawk 2, I think the version I compile had not included the fixes. I will try to compile with the lastest codes. Thank you.
