### ISSUE TITLE
[Automation tests] Fast Reload and COPP tests should be able to run on physical test beds instead of PTF 

### ISSUE THREAD

**Issue by sfardeen-li** [Azure/SONiC#108]
SONIC automation tests have a combination of tests. Few tests require physical test bed and few other run PTF simulation platform. Fast Reload and COPP tests are limited to PTF ony. They should be capable of running on physical test bed too.

**Comment by pavel-shirshov** [comment]
Hi,

What do you mean by physical test bed here?
We use ptf container to receive and send packets. It's just a way to be able communicate with DUT

**Comment by sfardeen-li** [comment]
Issue is not applicable any more hence closing.
