### ISSUE TITLE
SUGGESTION: Detail the supported CPU(s) on your wiki

### ISSUE THREAD

**Issue by pollyhsu2git** [Azure/SONiC#122]
Dear all,

On your *wiki*, we could tell the supported devices / platforms (https://github.com/Azure/SONiC/wiki/Supported-Devices-and-Platforms), however, there is no where we could find the info of your supported CPU(s), which is Intel x86 ONLY *currently*.

Suggestion:  Detail the supported CPU(s) on your wiki also

**Comment by lguohan** [comment]
added a note that only x86_64 CPU is supported. Once other CPU types are supported, will add there.
