### ISSUE TITLE
Sonic brcm image is not loading  from latest build #388

### ISSUE THREAD

**Issue by chitra-raghavan** [Azure/SONiC#123]
Sonic brcm Os is not loading from build 388. ( In S6100  ) .
Latest builds 390 and 391 also fails to load.

None of the dockers came up.   Image is loading fine in label 384.

	root@sonic:~# show version
	SONiC Software Version: SONiC.HEAD.388-d7969dd
	Distribution: Debian 8.9
	Kernel: 3.16.0-4-amd64
	Build commit: d7969dd
	Build date: Sat Nov 11 07:20:07 UTC 2017
	Built by: johnar@jenkins-worker-4
	
	Docker images:
	REPOSITORY          TAG                 IMAGE ID            SIZE
	
	root@sonic:~#
	root@sonic:~#
	root@sonic:~# docker ps
	CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
	root@sonic:~#
	root@sonic:~# bcmcmd ps
	Error response from daemon: No such container: syncd
	root@sonic:~#

**Comment by lguohan** [comment]
thanks for reporing the issue. do you use sonic_install to upgrade the image or use onie installer to install?

**Comment by chitra-raghavan** [comment]
This issue #123 , we did install from sonic_installer for s6100.
There is similar issue #347  seen in S6000  , for which we did onie-upgrade  , but the device doesn't come up. ( [https://github.com/Azure/sonic-mgmt/issues/347]

**Comment by stcheng** [comment]
hello @chitra-raghavan right now i'm using the version 
```
root@str-s6100-acs-5:/home/admin# show version
SONiC Software Version: SONiC.HEAD.347-cea87e9
Distribution: Debian 8.9                      
Kernel: 3.16.0-4-amd64                        
Build commit: cea87e9                         
Build date: Wed Nov 15 01:12:28 UTC 2017      
Built by: sonicbld@jenkins-slave-phx-1        
```
I don't see the issue you mentioned.

I am using the `sonic_installer` to install the image.

**Comment by stcheng** [comment]
I doubt if you don't have the DHCP configured on some DHCP server.
If you check the syslog, you might see waiting for DHCP reply and this might block all other dockers from being brought up. @taoyl-ms could you help check if that is the case?

**Comment by chitra-raghavan** [comment]
@stcheng , the image is loading fine in image 384

	root@sonic-s6100-01:/etc/sonic# show ver
	SONiC Software Version: SONiC.HEAD.384-4e367c6
	Distribution: Debian 8.9
	Kernel: 3.16.0-4-amd64
	Build commit: 4e367c6
	Build date: Thu Nov  9 05:14:32 UTC 2017
	Built by: johnar@jenkins-worker-3
	
	Docker images:
	REPOSITORY                TAG                 IMAGE ID            SIZE
	docker-syncd-brcm         HEAD.384-4e367c6    7ef7a9230eb2        317.2 MB
	docker-syncd-brcm         latest              7ef7a9230eb2        317.2 MB
	docker-orchagent-brcm     HEAD.384-4e367c6    f9098fd4e2d6        258.2 MB
	docker-orchagent-brcm     latest              f9098fd4e2d6        258.2 MB
	docker-lldp-sv2           HEAD.384-4e367c6    d806d924267d        255.4 MB
	docker-lldp-sv2           latest              d806d924267d        255.4 MB
	docker-dhcp-relay         HEAD.384-4e367c6    93d7bb38c9e0        252.4 MB
	docker-dhcp-relay         latest              93d7bb38c9e0        252.4 MB
	docker-database           HEAD.384-4e367c6    7d35cd816398        250.6 MB
	docker-database           latest              7d35cd816398        250.6 MB
	docker-snmp-sv2           HEAD.384-4e367c6    2bbfb5a201a8        290.2 MB
	docker-snmp-sv2           latest              2bbfb5a201a8        290.2 MB
	docker-teamd              HEAD.384-4e367c6    3540bc146643        255.3 MB
	docker-teamd              latest              3540bc146643        255.3 MB
	docker-platform-monitor   HEAD.384-4e367c6    69c875fffe4b        269.9 MB
	docker-platform-monitor   latest              69c875fffe4b        269.9 MB
	docker-fpm-quagga         HEAD.384-4e367c6    4510203b9265        261.8 MB
	docker-fpm-quagga         latest              4510203b9265        261.8 MB
	
	root@sonic-s6100-01:/etc/sonic#

**Comment by lguohan** [comment]
384 image was built using jenkins-worker-4 which has incorrect docker settings. I fixed the jenkins-worker-4 to the correct docker settings. The problem should be solved now. Unfortunately, image 384 is unusable. I removed all images that built by jenkins-worker-4. New build from jenkins-worker-4 will be fine. build from jenkins-worker-3 should also be good.
