### ISSUE TITLE
Configuration-with-Minigraph reference link broken

### ISSUE THREAD

**Issue by gite-ashish** [Azure/SONiC#124]
hi,

On https://github.com/Azure/SONiC/wiki/Quick-Start#configuration, the URL is broken:

> You can find a detailed description of the device minigraph "here"

"here" points to: https://github.com/Azure/SONiC/wiki/Configuration-and-Minigraph
But on searching a bit on wiki found the correct url with note: https://github.com/Azure/SONiC/wiki/Configuration-with-Minigraph-(~Sep-2017)

> (Before Sep 2017, we were using an xml file named Minigraph to configure SONiC devices. For historical documentation, please refer to Configuration with Minigraph)

May be, same note & updated url can be mentioned on: https://github.com/Azure/SONiC/wiki/Quick-Start#configuration

thx

**Comment by maggiemsft** [comment]
fixed, thanks @gite-ashish
