### ISSUE TITLE
Deploy topology error 

### ISSUE THREAD

**Issue by huanchen** [Azure/SONiC#127]
Execute  ./testbed-cli.sh add-topo vms-t1 ~ / .password
TASK eos: copy boot-config and build a startup config  occur error, 
the error message is as follows:
TASK [eos: copy boot-config] ***************************************** *********
Wednesday 29 November 2017 13:47:12 +0000 (0: 00: 00.418) 0: 02: 59.216 ****
fatal: [VM0100]: UNREACHABLE! => {"changed": false, "msg": "ERROR! Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permission on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in "/ tmp \". Failed command was: (umask 22 && mkdir -p \ "$ (echo $ HOME / .ansible / tmp / ansible-tmp- 1511963234.37-59276502553358) \ "&& echo \" $ (echo $ HOME / .ansible / tmp / ansible-tmp-1511963234.37-59276502553358) \ "), exited with result 1: \ u001b [5n \ r \ n> && mkdir -p \ "$ (echo $ HOME / .ansible / tmp / ansible-tmp-1511963234.37-59276502553358) \" && echo \ "$ (echo $ HOME / .ansible / tmp / ansible-tmp-1511963234.37-59276502553358) \ ") \ r \ n% Invalid input at line 1 \ r \ n", "unreachable": true}
Analysis of the reason, ansible using  SSH connection VM0100  execute  shell command unsuccessful, try to manual SSH connection， I find the VM0100 (vEOS 4.15.9M) working in CLI mode, rather than working in bash shell mode,
Please help analyze the reason，thanks，
the installation environment is in accordance with the README.testbed.Setup.md

**Comment by stcheng** [comment]
@maggiemsft do you have any idea?

**Comment by maggiemsft** [comment]
@huanchen 
I think after deploy of the initial Arista vms, the user root login should fall directly into shell. user admin login is cli.

could you check if your group_vars/eos/creds.yml is configured correctly for root? 
If you didn't change the vars in vm_set, it should be root/123456 I think

**Comment by huanchen** [comment]
using root / 123456, the problem is solved, tks!
