### ISSUE TITLE
Do I Need To Integrate Broadcom SDK in SONIC ?

### ISSUE THREAD

**Issue by muindurk** [Azure/SONiC#130]
I new to sonic and started porting SONIC (with latest GIT) for one of our platform (TomHawk based). Porting guide is much helpfull, and we able to build SONIC image with Platform-module.deb (driver) and Device module (Python script in plugins, sai-config, port_config, sensor.conf, minigraph .......) along with primary level of testing of Python scrips. As a next step we are expecting Ethernet ports to come up. The "show interface status" shows ports adminstartively N/A and "config interface startup Ethernet*" complaints with unknown port. The "ifconfig -a" utility does not show devies with Ethernet* name.
1)Are we missing anything?
2)Do we need to compile & install any Broadcom SDK or Package?
3)Is there any place we can find Broadcom log and/or error messages?
4)What is location Broadcom expect config.bcm file and at what point of initialization?

Thanks,
Mukund

[ifconfig-output.txt](https://github.com/Azure/SONiC/files/1535051/ifconfig-output.txt)
[show-interface.txt](https://github.com/Azure/SONiC/files/1535052/show-interface.txt)

**Comment by muindurk** [comment]
Adding Further
3)Is there any place we can find Broadcom log and/or error messages?
4)What is location Broadcom expect config.bcm file and at what point of initialization?

**Comment by lguohan** [comment]
you do not Broadcom sdk or package. sonic image comes with prebuilt SAI packages. 

However, you do need to provide the config.bcm to initialize the SAI. You can check the sai.profile section in the porting guide.

In your case, most likely it is the SAI init issues. You can find the sai logs in /var/log/syslog

**Comment by lguohan** [comment]
the issue is due to missing config.bcm. problem solved when proper config.bcm is supplied.
