### ISSUE TITLE
Old configuration support is broken

### ISSUE THREAD

**Issue by andriymoroz** [Azure/SONiC#133]
[The commit "[dockers] Remove dependency to minigraph"](https://github.com/Azure/sonic-buildimage/commit/dd7e9240c83f029cfdc9cd8c772c94de5bd19bb4) breaks the support of old minigraphs which do not have neighbors listed in section `<Devices>`.
Option "-m" for sonic-cfggen helped to generate empty DEVICE_NEIGHBOR_METADATA. Without it it is not generated and buffers configuration template fails.
New minigraphs work ok.

**Comment by liatgrozovik** [comment]
@andriymoroz does it mean that we need as part of sonic upgrade to generate new minigraph?
@lguohan what should be the preferred behaviour to a user? If i remember correct we discussed that we will have minigraph as backwards compatibility, if this is not the case any more we need to provide different guidelines for the users.
