### ISSUE TITLE
show ip route cmd implement problem

### ISSUE THREAD

**Issue by richard28530** [Azure/SONiC#144]
1.  show ip route, the output is ipv6 route
2. show ipv6 has no route sub-command 

admin@SONIC:~$ show ip
ip    ipv6
admin@SONIC:~$ show ip
bgp    route
admin@SONIC:~$ show ip route .
Command: sudo vtysh -c "show ipv6 route ."
% Unknown command.

admin@SONIC:~$ show ip route
Command: sudo vtysh -c "show ipv6 route"
Codes: K - kernel route, C - connected, S - static, R - RIPng,
       O - OSPFv6, I - IS-IS, B - BGP, A - Babel,
       > - selected route, * - FIB route

C>* ::1/128 is directly connected, lo
C * fe80::/64 is directly connected, Vlan1
C>* fe80::/64 is directly connected, eth0

admin@SONIC:~$ sudo vtysh -c "show ip route"
Codes: K - kernel route, C - connected, S - static, R - RIP,
       O - OSPF, I - IS-IS, B - BGP, P - PIM, A - Babel,
       > - selected route, * - FIB route

S>* 0.0.0.0/0 [200/0] via 169.254.30.1, eth0
C>* 12.18.0.0/27 is directly connected, Vlan1
C>* 100.0.0.9/32 is directly connected, lo
C>* 127.0.0.0/8 is directly connected, lo
C>* 169.254.30.0/24 is directly connected, eth0
C>* 240.127.1.0/24 is directly connected, docker0

admin@SONIC:~$ show version
SONiC Software Version: SONiC.201709.0-dirty
Distribution: Debian 8.1
Kernel: 3.16.0-4-amd64
Build commit: 379451e
Build date: Fri Jan 12 09:15:49 UTC 2018
Built by: chenhu@localhost

Docker images:
REPOSITORY                TAG                 IMAGE ID            SIZE
docker-syncd-nephos       latest              0e5fd93aed47        280.5 MB
docker-orchagent-nephos   latest              51ff563ba344        257.3 MB
docker-dhcp-relay         latest              be41b005f0e9        252.4 MB
docker-database           latest              38c4af5c619e        250.6 MB
docker-snmp-sv2           latest              f3e7e6550b12        290.2 MB
docker-teamd              latest              f57385460b92        254.3 MB
docker-platform-monitor   latest              b8a796e694b2        269.9 MB
docker-lldp-sv2           latest              5c74743b3af1        255.4 MB
docker-fpm-quagga         latest              4a325d50e76b        260.9 MB

**Comment by prsunny** [comment]
Not sure why your `"show ip route"` command is invoking `Command: sudo vtysh -c "show ipv6 route"`

Can you open the file ./usr/lib/python2.7/dist-packages/show/main.py in your DUT and check route subcommand?

**Comment by richard28530** [comment]
https://github.com/Azure/sonic-utilities/blob/77c9f811d23dd83abc4bc429b329a5e50a2abba6/show/main.py#L373

branch 201709 uses a very old version of sonic-utilities(about 3 month ago)，that version has the problem
