### ISSUE TITLE
Ports not coming up on AS5712-54x

### ISSUE THREAD

**Issue by 1456055067** [Azure/SONiC#153]
Interfaces not coming up, After config added to config_db.json

Command: intfutil status
  Interface    Lanes    Speed    MTU      Alias    Oper    Admin
-----------  -------  -------  -----  ---------  ------  -------
  Ethernet0       13      N/A    N/A   tenGigE0     N/A      N/A
  Ethernet1       14      N/A    N/A   tenGigE1     N/A      N/A
  Ethernet2       15      N/A    N/A   tenGigE2     N/A      N/A
  Ethernet3       16      N/A    N/A   tenGigE3     N/A      N/A
  Ethernet4       21      N/A    N/A   tenGigE4     N/A      N/A
  Ethernet5       22      N/A    N/A   tenGigE5     N/A      N/A
  Ethernet6       23      N/A    N/A   tenGigE6     N/A      N/A
  Ethernet7       24      N/A    N/A   tenGigE7     N/A      N/A
  Ethernet8       25      N/A    N/A   tenGigE8     N/A      N/A
  Ethernet9       26      N/A    N/A   tenGigE9     N/A      N/A
 Ethernet10       27      N/A    N/A  tenGigE10     N/A      N/A
 Ethernet11       28      N/A    N/A  tenGigE11     N/A      N/A
 Ethernet12       29      N/A    N/A  tenGigE12     N/A      N/A
 Ethernet13       30      N/A    N/A  tenGigE13     N/A      N/A
 Ethernet14       31      N/A    N/A  tenGigE14     N/A      N/A
 Ethernet15       32      N/A    N/A  tenGigE15     N/A      N/A

**Comment by pollyhsu2git** [comment]
@lguohan, is your new SAI [3.1.3.4] ruling out the the TD2:  info dev value as 0xb854 as we reported it on your SAI [3.0.3.2] release via https://github.com/Azure/sonic-buildimage/issues/1054.

root@sonic:/home/admin# show ver
SONiC Software Version: SONiC.master.0-126d08d
Distribution: Debian 8.10
Kernel: 3.16.0-5-amd64
Build commit: 126d08d
Build date: Mon Mar  5 07:21:42 UTC 2018

**Comment by pollyhsu2git** [comment]
@1456055067, if your syslog had the same ERROR / CRIT messages as ours, the cause of your issue might be the same as ours.

**Comment by pollyhsu2git** [comment]
@1456055067, We've verified that the TD2 b854 is supported on SONiC.HEAD.518-913a62c.
