### ISSUE TITLE
AS5712-54X fails to establish link to cisco 6509

### ISSUE THREAD

**Issue by 1456055067** [Azure/SONiC#156]
We are having issues getting the Edgecore AS5712-54X to establish a link to a Cisco 6509. The SFP is transmitting on both sides and all is configured correctly, establishes link fine when we connect it to a server. Any thoughts?

**Comment by 1456055067** [comment]
@pollyhsu2git The 6509 will connect to the server and the edge core will as well. The same SFPs are used on both ends but the Edgecore and 6509 won't talk to each other.

**Comment by pollyhsu2git** [comment]
@1456055067, The syslog of your tested Edgecore AS5712-54X ***`might`*** have the clues of it.
