### ISSUE TITLE
wiki TOC Building Guide link to  sonic-buildimage but not the wiki page

### ISSUE THREAD

**Issue by sunnogo** [Azure/SONiC#165]
Hi, 

I find that there's a wiki page [Building Guide](https://github.com/Azure/SONiC/wiki/Building-Guide), but the TOC "For Developers" -> "Building Guide" link to https://github.com/Azure/sonic-buildimage/blob/master/README.md directly.

Regards,
Jerome Sun

**Comment by lguohan** [comment]
corrected. Thanks for reporting.
