### ISSUE TITLE
[Debian9] RX Traffic drop seen when l3 traffic was enabled with qos dscp 3 and 4 on S6100 SONIC

### ISSUE THREAD

**Issue by mfriyas** [Azure/SONiC#166]
Test setup:-

Traffic generator --------- sonic

Description:- 
I am having 3 traffic generator ports [Ixia] connected to sonic device. When am sending traffic from port1 and port3 to port2 with dscp enabled as 3 and 4 [on port 1 as dscp3 and port 3 as dscp4]. I am seeing traffic RX drop on sonic device running with latest debian 9. 

If removed dscp 3 & 4 from taffic pattern, the traffic flows to the destination without drop.

This issue was not seen earlier in debian 8.

Configuration on sonic and steps to repro-

connect 3 ports  from sonic S6100  to traffic generator
enable ip address on sonic for port1 as 1.1.1.1/24 , port2 as 2.2.2.1/24 & port3 as 3.3.3.1
enable ip address on traffic generator for port1 as 1.1.1.2/24,port2 as 2.2.2.2/24 & port3 as 3.3.3.2
send traffic from port1 and port3 to port2 with dscp enabled as 3 and 4 [on port 1 as dscp value 3 and port 3 as dscp value 4]
verify show interface counters 

Logs:-
Packet Drop with DSCP enabled:-

root@sonic:/home/admin# show interfaces counters
Command: portstat
     IFACE    STATE     RX_OK    RX_BPS    RX_UTIL    RX_ERR    RX_DRP    RX_OVR    TX_OK    TX_BPS    TX_UTIL    TX_ERR    TX_DRP    TX_OVR
----------  -------  --------  --------  ---------  --------  --------  --------  -------  --------  ---------  --------  --------  --------
 Ethernet0        U  18897565       N/A        N/A         0        18936790         0        3       N/A        N/A         0         0         0
 Ethernet1        D         0       N/A        N/A         0         0         0        0       N/A        N/A         0         0         0
 Ethernet2        X         0       N/A        N/A         0         0         0        0       N/A        N/A         0         0         0
 Ethernet3        X         0       N/A        N/A         0         0         0        0       N/A        N/A         0         0         0
 Ethernet4        U         0       N/A        N/A         0         0         0        3       N/A        N/A         0         0         0
 Ethernet5        D         0       N/A        N/A         0         0         0        0       N/A        N/A         0         0         0
 Ethernet6        D         0       N/A        N/A         0         0         0        0       N/A        N/A         0         0         0
 Ethernet7        D         0       N/A        N/A         0         0         0        0       N/A        N/A         0         0         0
 Ethernet8        U  17222336       N/A        N/A         0  17270986         0        4       N/A        N/A         0         0         0 
 
**No Traffic drop without DSCP marking**

root@sonic:/home/admin# show interfaces counters
Command: portstat
     IFACE    STATE    RX_OK    RX_BPS    RX_UTIL    RX_ERR    RX_DRP    RX_OVR     TX_OK    TX_BPS    TX_UTIL    TX_ERR    TX_DRP    TX_OVR
----------  -------  -------  --------  ---------  --------  --------  --------  --------  --------  ---------  --------  --------  --------
Ethernet0        U  5970083       N/A        N/A         0         0         0         0       N/A        N/A         0         0         0
Ethernet1        D        0       N/A        N/A         0         0         0         0       N/A        N/A         0         0         0
Ethernet2        X        0       N/A        N/A         0         0         0         0       N/A        N/A         0         0         0
Ethernet3        X        0       N/A        N/A         0         0         0         0       N/A        N/A         0         0         0
Ethernet4        U        0       N/A        N/A         0         0         0                            12070695       N/A        N/A         0         0         0
Ethernet5        D        0       N/A        N/A         0         0         0         0       N/A        N/A         0         0         0
Ethernet6        D        0       N/A        N/A         0         0         0         0       N/A        N/A         0         0         0
Ethernet7        D        0       N/A        N/A         0         0         0         0       N/A        N/A         0         0         0
Ethernet8        U  6070583       N/A        N/A         0         0         0         0       N/A        N/A         0         0         0
Ethernet9        D        0       N/A        N/A         0         0         0

root@sonic:/home/admin# arp
Address                  HWtype  HWaddress           Flags Mask            Iface
1.1.1.2                  ether   00:00:61:70:d1:98   C                     Ethernet0
10.16.151.252      ether   90:b1:1c:f4:e7:6b   C                     eth0
10.16.208.104      ether   90:b1:1c:f4:e7:6b   C                     eth0
3.3.3.2                  ether   00:00:61:71:33:40   C                     Ethernet8
2.2.2.2                  ether   00:00:61:71:08:a6   C                     Ethernet4
root@sonic:/home/admin#

root@sonic:/home/admin# show version
SONiC Software Version: SONiC.HEAD.161-7c8a635
Distribution: Debian 9.4
Kernel: 4.9.0-5-amd64
Build commit: 7c8a635
Build date: Tue Apr  3 11:25:06 UTC 2018
Built by: johnar@jenkins-worker-4

Docker images:
REPOSITORY                 TAG                 IMAGE ID            SIZE
docker-syncd-brcm          HEAD.161-7c8a635    263bcbed3b14        358.1 MB
docker-syncd-brcm          latest              263bcbed3b14        358.1 MB
docker-orchagent-brcm      HEAD.161-7c8a635    f5326eae6970        287 MB
docker-orchagent-brcm      latest              f5326eae6970        287 MB
docker-lldp-sv2            HEAD.161-7c8a635    d77ff6995334        297.1 MB
docker-lldp-sv2            latest              d77ff6995334        297.1 MB
docker-dhcp-relay          HEAD.161-7c8a635    92ada5e29818        280.1 MB
docker-dhcp-relay          latest              92ada5e29818        280.1 MB
docker-database            HEAD.161-7c8a635    746e6563e61f        278.7 MB
docker-database            latest              746e6563e61f        278.7 MB
docker-teamd               HEAD.161-7c8a635    b7ac2067fd06        284.1 MB
docker-teamd               latest              b7ac2067fd06        284.1 MB
docker-snmp-sv2            HEAD.161-7c8a635    7096ad720bf0        319.2 MB
docker-snmp-sv2            latest              7096ad720bf0        319.2 MB
docker-router-advertiser   HEAD.161-7c8a635    a78cf51c9c00        276.4 MB
docker-router-advertiser   latest              a78cf51c9c00        276.4 MB
docker-platform-monitor    HEAD.161-7c8a635    072d237209c4        298.3 MB
docker-platform-monitor    latest              072d237209c4        298.3 MB
docker-fpm-quagga          HEAD.161-7c8a635    02f60ab8b7b5        290.6 MB
docker-fpm-quagga          latest              02f60ab8b7b5        290.6 MB

root@sonic:/home/admin#

**Comment by mfriyas** [comment]
Hi Added here the build version

root@sonic:/home/admin# show version
SONiC Software Version: SONiC.HEAD.161-7c8a635
Distribution: Debian 9.4
Kernel: 4.9.0-5-amd64
Build commit: 7c8a635
Build date: Tue Apr 3 11:25:06 UTC 2018
Built by: johnar@jenkins-worker-4

**Comment by mfriyas** [comment]
The same  issue was reported in latest Debian 8. SONiC.HEAD.570-d117172

root@sonic:/home/admin# show version
SONiC Software Version: SONiC.HEAD.570-d117172
Distribution: Debian 8.10
Kernel: 3.16.0-5-amd64
Build commit: d117172
Build date: Wed Apr 25 11:47:26 UTC 2018
Built by: johnar@jenkins-worker-4

**Comment by lguohan** [comment]
we have improve qos in 201807 release. We do not see such problem any more.
