### ISSUE TITLE
Unable to boot on Arista 7050QX-32S: /host/image-HEAD.547-4754b43/fs.squashfs does not exist.

### ISSUE THREAD

**Issue by erikpu** [Azure/SONiC#169]
When trying to boot SONiC on Arista 7050QX-32S, after some output, the following message appears:

```
[ 1253.574063] Starting new kernel
[    1.931211] i8042: No controller found
Loading, please wait...
[    3.491758] sd 2:0:0:0: [sda] No Caching mode page found
[    3.555322] sd 2:0:0:0: [sda] Assuming drive cache: write through
fsck from util-linux 2.25.2
/dev/sda1: clean, 22153/244800 files, 409931/978767 blocks
ALERT! /host/image-HEAD.547-4754b43/fs.squashfs does not exist.  Dropping to a shell!
modprobe: module ehci-orion not found in modules.dep


BusyBox v1.22.1 (Debian 1:1.22.0-9+deb8u1) built-in shell (ash)
Enter 'help' for a list of built-in commands.

/bin/sh: can't access tty; job control turned off
(initramfs)
```

This leaves me in the 'initramfs'-shell. What to do?

**Comment by maq123** [comment]
First of all, you did not specify how you are initiating the image so your issue is incomplete.
I hope you do it exactly as described here: https://github.com/Azure/SONiC/wiki/Quick-Start
Try it and let us know.

**Comment by erikpu** [comment]
The Arista-device provides Aboot to boot the OS. I used the command `boot` in the Aboot-CLI to boot the SONiC image I have stored on an HTTP server connected with a serial console to the Arista.

**Comment by maq123** [comment]
Provide the full command.
Read the docs beforehand.

**Comment by erikpu** [comment]
`boot http://192.168.250.1/sonic-aboot-broadcom.swi`

**Comment by maq123** [comment]
Now go and read the docs...
