### ISSUE TITLE
Need a CLI to enable/disable FEC

### ISSUE THREAD

**Issue by hein2ren** [Azure/SONiC#176]
By default, FEC is enabled on the Barefoot switches. Other platforms running SONiC (i.e. AG9032), FEC is disabled by default. This behavior creates interop issue.

We need to have a CLI to enable/disable FEC so that we can configure it to match the peer devices. The workaround currently is to get to the Barefoot shell prompt and enable/disable FEC. However, the change isn't persistent. Once the box is reloaded, the changes are gone.

**Comment by dpanth3r** [comment]
I believe this issue was solved in the latest version of `portconfig`.

**Comment by lguohan** [comment]
Yes, portconfig support set FEC now.

```
admin@str-s6000-on-4:~$ portconfig
usage: portconfig [-h] [-v] -p PORT [-l] [-s SPEED] [-f FEC] [-vv]
```
