### ISSUE TITLE
integrate firmware upgrade in the syncd docker deployment process on mlnx platform

### ISSUE THREAD

**Issue by lguohan** [Azure/SONiC#18]
syncd docker containers mlnx sdk and it has to match the firmware in order to run. When deploying a new syncd docker with a new version of mlnx sdk, it requires to upgrade the firmware. Currently this is not embed in the syncd docker deployment process in the ansible. 

We need to upgrade the firmware when rolling out a new mlnx sdk. We prefer to embed the mlnx firmware inside the syncd docker, and then calling mlnxfwmanager to upgrade the firmware when there is a new firmware.

**Comment by marian-pritsak** [comment]
Created pull request

https://github.com/Azure/sonic-buildimage/pull/31
