### ISSUE TITLE
BGP timers are hard-coded in SONiC

### ISSUE THREAD

**Issue by hein2ren** [Azure/SONiC#180]
The BGP timers are hard-coded. The keepalive is set to 60 seconds and the holdtime is set to 180 seconds. Even when I configured 10 seconds keepalive and 30 seconds hold time, the BGP sessions come up with the hard-coded values. The runningconfiguration doesn't show the BGP timers also. It appears that the timers configured in the config_db.json are . ignored.

roger@AG9032-54-SONIC-SPINE1:~$ show version
SONiC Software Version: SONiC.master.0-d64658b
Distribution: Debian 8.10
Kernel: 3.16.0-5-amd64
Build commit: d64658b
Build date: Fri Feb 16 09:48:23 UTC 2018
Built by: duobliu@ubuntu

Configurations
----------------
"BGP_NEIGHBOR": {
"10.100.1.1":

{ "rrclient": 0, "name": "AG7648-38-LEAF1", "local_addr": "10.100.1.2", "nhopself": 0, "holdtime": "30", "asn": "64515", "keepalive": "10" }
, 
"10.100.2.1":

{ "rrclient": 0, "name": "AG9064-45-SONIC-LEAF2", "local_addr": "10.100.2.2", "nhopself": 0, "holdtime": "30", "asn": "64516", "keepalive": "10" }
},

BGP Neighbor
---------------

BGP neighbor is 10.100.2.1, remote AS 64516, local AS 65001, external link
Description: AG9064-45-SONIC-LEAF2
BGP version 4, remote router ID 10.10.1.2
BGP state = Established, up for 23:17:03
Last read 00:00:02, hold time is 180, keepalive interval is 60 seconds
Neighbor capabilities:
4 Byte AS: advertised and received
Route refresh: advertised and received(old & new)
Address family IPv4 Unicast: advertised and received
Graceful Restart Capabilty: advertised and received
Remote Restart timer is 120 seconds
Address families by peer:
none
Graceful restart informations:
End-of-RIB send: IPv4 Unicast
End-of-RIB received: IPv4 Unicast
Message statistics:
Inq depth is 0
Outq depth is 0
Sent Rcvd
Opens: 7 4
Notifications: 1 4
Updates: 129 167
Keepalives: 11443 11437
Route Refresh: 0 0
Capability: 0 0
Total: 11580 11612
Minimum time between advertisement runs is 30 seconds

For address family: IPv4 Unicast
Community attribute sent to this neighbor(both)
10 accepted prefixes

Connections established 6; dropped 5
Last reset 23:17:16, due to BGP Notification received
Local host: 10.100.2.2, Local port: 37155
Foreign host: 10.100.2.1, Foreign port: 179
Nexthop: 10.100.2.2
Nexthop global: fe80::218:23ff:fe30:e62e
Nexthop local: ::
BGP connection: non shared network
Read thread: on Write thread: off

BGP runningconfiguratrion

----------------------------

roger@AG9032-54-SONIC-SPINE1:~$ show runningconfiguration bgp
Command: sudo vtysh -c "show running-config"
Building configuration...

Current configuration:
!
hostname AG9032-54-SONIC-SPINE1
log syslog informational
log facility local4
!
password zebra
enable password zebra
!
interface Bridge
ipv6 nd suppress-ra
no link-detect
!
interface Ethernet0
ipv6 nd suppress-ra
link-detect
!
interface Ethernet4
ipv6 nd suppress-ra
link-detect
!
interface Ethernet8
ipv6 nd suppress-ra
no link-detect
!
interface Ethernet12
ipv6 nd suppress-ra
no link-detect
!
interface Ethernet16
ipv6 nd suppress-ra
no link-detect
!
interface Ethernet20
ipv6 nd suppress-ra
no link-detect
!
interface Ethernet24
ipv6 nd suppress-ra
no link-detect
!
interface Ethernet28
ipv6 nd suppress-ra
no link-detect
!
interface Ethernet32
ipv6 nd suppress-ra
no link-detect
!
interface Ethernet36
ipv6 nd suppress-ra
no link-detect
!
interface Ethernet40
ipv6 nd suppress-ra
no link-detect
!
interface Ethernet44
ipv6 nd suppress-ra
no link-detect
!
interface Ethernet48
ipv6 nd suppress-ra
no link-detect
!
interface Ethernet52
ipv6 nd suppress-ra
no link-detect
!
interface Ethernet56
ipv6 nd suppress-ra
no link-detect
!
interface Ethernet60
ipv6 nd suppress-ra
no link-detect
!
interface Ethernet64
ipv6 nd suppress-ra
no link-detect
!
interface Ethernet68
ipv6 nd suppress-ra
no link-detect
!
interface Ethernet72
ipv6 nd suppress-ra
no link-detect
!
interface Ethernet76
ipv6 nd suppress-ra
no link-detect
!
interface Ethernet80
ipv6 nd suppress-ra
no link-detect
!
interface Ethernet84
ipv6 nd suppress-ra
no link-detect
!
interface Ethernet88
ipv6 nd suppress-ra
no link-detect
!
interface Ethernet92
ipv6 nd suppress-ra
no link-detect
!
interface Ethernet96
ipv6 nd suppress-ra
no link-detect
!
interface Ethernet100
ipv6 nd suppress-ra
no link-detect
!
interface Ethernet104
ipv6 nd suppress-ra
no link-detect
!
interface Ethernet108
ipv6 nd suppress-ra
no link-detect
!
interface Ethernet112
ipv6 nd suppress-ra
no link-detect
!
interface Ethernet116
ipv6 nd suppress-ra
no link-detect
!
interface Ethernet120
ipv6 nd suppress-ra
no link-detect
!
interface Ethernet124
ipv6 nd suppress-ra
no link-detect
!
interface bcm0
ipv6 nd suppress-ra
no link-detect
!
interface docker0
ipv6 nd suppress-ra
no link-detect
!
interface eth0
ipv6 nd suppress-ra
no link-detect
!
interface lo
no link-detect
!
router bgp 65001
bgp router-id 10.10.2.1
bgp log-neighbor-changes
no bgp default ipv4-unicast
bgp bestpath as-path multipath-relax
network 10.10.2.1/32
neighbor 10.100.1.1 remote-as 64515
neighbor 10.100.1.1 description AG7648-38-LEAF1
neighbor 10.100.1.1 activate
neighbor 10.100.2.1 remote-as 64516
neighbor 10.100.2.1 description AG9064-45-SONIC-LEAF2
neighbor 10.100.2.1 activate
maximum-paths 64
!
route-map RM_SET_SRC permit 10
set src 10.10.2.1
!
route-map FROM_BGP_SPEAKER_V4 permit 10
!
route-map TO_BGP_SPEAKER_V4 deny 10
!
route-map ISOLATE permit 10
set as-path prepend 65001
!
ip forwarding
ipv6 forwarding
!
ip protocol bgp route-map RM_SET_SRC
!
line vty
!
end

roger@AG9032-54-SONIC-SPINE1:~$

Options
Click here to Reply

**Comment by pavel-shirshov** [comment]
Please check the PR: https://github.com/Azure/sonic-buildimage/pull/1661
