### ISSUE TITLE
ARP entries are not being restored to Linux during fast reboot

### ISSUE THREAD

**Issue by denis-maslov** [Azure/SONiC#192]
ARP table in Linux **before** fast reboot:
```
admin@micro-2:~$ show arp
Command: /usr/sbin/arp -n
Address                  HWtype  HWaddress           Flags Mask            Iface
10.7.0.1                 ether   5c:5e:ab:6c:06:c1   C                     eth0
10.20.1.32               ether   00:10:94:00:00:01   C                     Vlan10
```
APR entries in redis-db (database 0) **before** fast reboot:
```
admin@micro-2:~$ redis-cli 
127.0.0.1:6379> keys *NEI*
1) "NEIGH_TABLE:Vlan10:10.20.1.32"
2) "NEIGH_TABLE:lo:127.0.0.1"
3) "NEIGH_TABLE:eth0:10.7.0.1"
```
ARP table in Linux **after** fast reboot:
```
admin@micro-2:~$ show arp
Command: /usr/sbin/arp -n
Address                  HWtype  HWaddress           Flags Mask            Iface
10.7.0.1                 ether   5c:5e:ab:6c:06:c1   C                     eth0
```
APR entries in redis-db (database 0) **after** fast reboot:
```
127.0.0.1:6379> keys *NEI*
1) "NEIGH_TABLE:lo:127.0.0.1"
2) "NEIGH_TABLE:eth0:10.7.0.1"
3) "NEIGH_TABLE:Vlan10:10.20.1.32"
```
Content of **/arp.json** file (**swss** container) during fast reboot:
```
[
  {
    "NEIGH_TABLE:Vlan10:10.20.1.32": {
      "neigh": "00:10:94:00:00:01",
      "family": "IPv4"
    },
    "OP": "SET"
  }
]
```

**Comment by pavel-shirshov** [comment]
Hi Denis.

I don't think this is an issue. We care about the data plane only in the fast-reboot procedure. Our goal is to restore functionality of a device ASAP.
Also control plane arp table (Linux arp table in this case) is a source information for SONiC. In the FR procedure we don't use this source, preferring the file instead.

Let me know if you have other questions.

**Comment by NStetskovych** [comment]
@pavel-shirshov in such case SONiC would not represent the actual state of the system.
 And the other question here is that arp requests will be send again after FR.

**Comment by pavel-shirshov** [comment]
Hi Nadiya,

I agree with your argument.
I'm ready to approve a PR fixing this issue. :)
Personnaly I don't know how to implement dynamic ARP entries in the Linux kernel.
Any suggestions?

**Comment by prsunny** [comment]
Essentially you would have to trigger ARP requests for the restored ARP entries after FB. This way kernel will relearn the ARP.

**Comment by pavel-shirshov** [comment]
As I remember from the kernel sources, the Linux kernel treats GARP worse than regular ARP.
I think we can use  `arp [-v] [-H type] [-i if] -s hostname hw_addr [temp]` `temp` parameter from the standard arp procedure. I'll check it today.

**Comment by NStetskovych** [comment]
@pavel-shirshov   ’ip nei add 10.20.1.2 lladdr 00:10:94:00:00:05 nud reachable dev Vlan10’ will add dynamic arp, but we do not sure the right place to put  this ( instead of swssconfig /arp.json ? : https://github.com/Azure/sonic-buildimage/blob/243a87d6e60fa045369d088855b7ab3e3f5d51f9/dockers/docker-orchagent/swssconfig.sh#L16

**Comment by prsunny** [comment]
My point is, if there is any change to ARP entry that happened during the downtime, (like MAC change or host down), we would be forwarding traffic to the wrong interface until the ARP expiry in kernel and hence suggested to _trigger_ ARP request after FB so as to resolve and relearn. Anyways just a thought!
