### ISSUE TITLE
Questions about Vlan feature test

### ISSUE THREAD

**Issue by ForzaTian** [Azure/SONiC#197]
Now I'm doing protocol test on our board base on [Testing-Guide](https://github.com/Azure/SONiC/wiki/Testing-Guide), but as for [Vlan feature test](https://github.com/Azure/SONiC/wiki/VLAN-Feature-Test-Suite), I have something not understand.
1. As my known, the example DUT used in VLAN L3 Traffic Test has 32 ports, 4 ports used as lag connected with VM, and 24 ports in one vlan and connected with PTF, but what about another 4 ports? Are they idle or connetced  with PTF? How to config them?
2. Who send packets? VM or the 4 injected ports of PTF or the 28 direct ports of PTF?
3. What's the correct result of procedure 5? The packets will flooding in vlan ports?
4. By reading VLAN L2 Traffic Test Guid, it seems there are 16 members in one vlan, it's different from VLAN L3 Traffic Test (24 members), why is that? 
5. Similar as question 2, Who send packets in VLAN L2 Traffic Test? It seems different between L3 and L2 test.

I have read the related contents in sonic-mgmt, by still have no ideas. Since I don't have Testbed Server, only IXIA on hand. So I want to know the principle of the test and then build my topology.
If you know any answer of those questions, please reply me.
 Many thanks for everyone.

**Comment by prsunny** [comment]
1. Those 4 ports are kept _admin_ down and not connected to PTF
2. For L3 test, the packets is send from one of the LAG interface to the downlink (Vlan interface)
3. In my understanding, the packet shall not be L3 forwarded if the IP is removed
4. Both test has the same configuration. 
5. In Vlan L2 (FDB test), the packet is send from one member port to the rest.

@stcheng can confirm and modify the "Vlan feature test" page if there is any ambiguties.
