### ISSUE TITLE
add portalias field in PORT_TABLE

### ISSUE THREAD

**Issue by lguohan** [Azure/SONiC#20]
extend the port_config.ini format to have a port alias for each port. add a port alias field in the PORT_TABLE schema. populate port alias field in portsyncd.

This port alias will be used for by snmp subagent as the interface alias.

**Comment by lguohan** [comment]
port_config.ini current format: 

    # alias         lanes
    Ethernet0       29,30,31,32
    Ethernet4       25,26,27,28


port_config.ini future format. The alias can be optional, when there is no such field, then it won't appear in the port_table as well.

    # name         lanes                alias
    Ethernet0       29,30,31,32     fortyGigE0/0
    Ethernet4       25,26,27,28     fortyGigE0/4

In the app db, port_tabel entry will has a new field/value. 

    127.0.0.1:6379> hgetall "PORT_TABLE:Ethernet0"
    1) "lanes"
    2) "29,30,31,32"
    3) "admin_status"
    4) "up"
    5) "oper_status"
    6) "up"
    7) "mtu"
    8) "1500"
    9) "alias"
    10) "fortyGigE0/0"

**Comment by stcheng** [comment]
resolved
