### ISSUE TITLE
Is there a document on commands that can change settings of SONiC?

### ISSUE THREAD

**Issue by doicom** [Azure/SONiC#219]
Hi all,

Someone, please help us.

I am looking for a command that can change SONIC's settings like cisco's set command.
In the Sonic configuration change command, only [vlan config] listed in the command reference was found.
Is there a setting command like cisco's set command apart from the show command?

If possible, please tell me the source code part (sonic-swss?) That uses the API (SAI etc.).

doicom

**Comment by ForzaTian** [comment]
May be you can use "vtysh" to enter into quagga cli, it's cisco command like.

**Comment by maq123** [comment]
hi @doicom ,

yes, there is, it is called 'config' press <tab> twice to get the available options.
Here you can read more: https://github.com/Azure/SONiC/wiki/Configuration

**Comment by doicom** [comment]
Hello, @maq123 .
thank you for answering.

Change of / etc / sonic / config_db.json.
  Thank you very much.

I installed SONiC on Accton-AS 7712-32X.
100 GNIC card and AS 7712 - 32 X can not be linked.
Can I set Link_up by changing config_db.json?

I am reading the following, but I can not Linkup.
https://github.com/Azure/SONiC/wiki/Port-Breakout-High-Level-Design
https://github.com/Azure/SONiC/wiki/Port-Speed-Configuration
https://github.com/Azure/SONiC/wiki/How-to-breakout-a-port


doicom

**Comment by maq123** [comment]
You can configure the interface just by using standard linux commands i.e. ip, ifconfig.

**Comment by doicom** [comment]
Hello, @ maq 123.
thank you for answering.

Is it said that Linuxcomand IP can be used to configure the interface?
Is it necessary procedure for link up?

**Comment by maq123** [comment]
No, it is not.
If you have your config_db.json up the link should be enabled on sonic startup.
But for testing, it is good to be able to use regular commands.

**Comment by doicom** [comment]
Hello, @ maq 123.
thank you for answering.

I'm sorry, my reaction was delayed.
When setting config_db.json, link up was possible.
Thank you very much.

However, Linkup can only be executed on 40G.
I am investigating the cause, but do you know any hints or other causes?

Platform: x86 - 64 - accton - as 7712 _ 32 x - r 0
OS: https: // sonic-jenkins.westus2.cloudapp.azure.com/job/broadcom/job/buildimage-brcm-all/lastSuccessfulBuild/artifact/target/sonic-broadcom.bin (DL in 2018/08/06)

**Comment by pollyhsu2git** [comment]
@doicom 
For the command level, you may try **config interface speed**
root@sonic:/home/admin# config interface speed
Usage: config interface speed [OPTIONS] <interface_name> <interface_speed>

**Comment by jleveque** [comment]
@doicom: Please refer to the SONiC Command Line Reference Guide for an overview of available commands: https://github.com/Azure/SONiC/wiki/Command-Reference

**Comment by doicom** [comment]
@ Pollyhsu 2 git
@ jleveque
Thank you for your answer.


@ Pollyhsu 2 git
thank you for answering.

<config interface speed Ehternet 80 100000> I did this.
I was able to confirm that the speed changed with <show interface state>.
However, it will not be linked. (Even if it returns to the original speed)


Ethtool can not check the cause with <no data>.

Is there a command to turn auto-negotiation on / off with <ethtool> of SONiC command?

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

@ jleveque
thank you for answering.

@ jleveque
On wiki, <portconfig - p> can change the port speed.
However, it is not described in the command reference.
I think the commands to change the settings are described separately.
Can I use a SONiC command that is not listed in the command reference?

Example)
<https://github.com/Azure/sonic-utilities/blob/master/scripts/portconfig>

**Comment by doicom** [comment]
Hello, @jleveque .
thank you for answering.
I'm sorry, my reaction was delayed.

I did not understand why the command described in the source is not listed in the command reference.
I understood that with your answer.

Thank you.
