### ISSUE TITLE
about Dtel

### ISSUE THREAD

**Issue by andrewhubo** [Azure/SONiC#222]
Hi,
I would like to know more about Dtel. Who can kindly share some info?
Thanks in advance!

**Comment by arkadiyshapiro** [comment]
Hi
Please review design document: https://github.com/shruthi9/SONiC/blob/013fff1f4c9dd15005cd83fd1da0f2cafe5ba039/doc/barefoot_dtel/Dtel-SONiC.md

Arkadiy Shapiro
Product Line Manager, Barefoot Networks
Mobile: 408-410-3189
E-mail: arkadiy@barefootnetworks.com

**Comment by andrewhubo** [comment]
Thanks a lot!

**Comment by xjtufjj** [comment]
is there code for this feature?
