### ISSUE TITLE
I would like to know how to set up a static route.

### ISSUE THREAD

**Issue by doicom** [Azure/SONiC#241]
Hi all,
I am sorry to leave a similar question.

Is it possible to set a static route?
If possible, please tell me the command to set static route and how to use quagga.

BGP is set in `config_db.json` of DL SONIC binary.
Is there a way to delete BGP settings?
Changed `config_db.json`. But it remains in the process.

The MAC address value of each port is the same setting, is this correct?
I think each port will be a different MAC address.

doicom

**Comment by shine4chen** [comment]
I try to answer you question:
1. you can use "ip route add xxx" to add a static route in kernel. Then quagga would get notification from kernel and propagate it to fpmsyncd and eventually to SAI.
2. after changed config_db.json you need to reload switch or use config load to reload config.
3. Different switch port can use same mac address. It is no problem.

**Comment by doicom** [comment]
Hi,@shine4chen 
Thank you for your reply.

`after changed config_db.json you need to reload switch or use config load to reload config.`
After changing config_db.json, I am doing "sudo reboot".
reload switch ＝"sudo reboot"？
Does it have to be set even in Kugaga?

`Different switch port can use same mac address. It is no problem.`

If it is L2, I'd use the MAC address of the device.
In L3, different values will be used for each port.
I am trying to assign a different MAC value to the port.
Is my way of thinking wrong?

doicoom

**Comment by shine4chen** [comment]
@doicom 
quagga configuration is generated from config_db.json. So no need to change quagga config.
In fact All L3 interface can share one mac address too. Sonic system use eth0 mac address for all L2 and L3 interface.

**Comment by doicom** [comment]
Hi,@shine4chen
Thank you for your reply.
Thanks to you, the mystery has been resolved.

`quagga configuration is generated from config_db.json. So no need to change quagga config.`

I was thinking about configuring OSPF with quagga.
Can I also configure OSPF from config_db.json?
If so, please tell me the format.

`
All L3 interfaces can also share one MAC address. The Sonic system uses the eth0 mac address for all L2 and L3 interfaces.`

I understood the reason for one MAC address.
Is it possible for the user to arbitrarily change the MAC address of the port?
I want to know if that is possible or impossible.

Example) I want to change the Ethernet 30
eth0 hw cc: 37: ab: c 8: 54: 0 a
Ethernet 28 hw cc: 37: ab: c 8: 54: 0 a
Ethernet 30 hw cc: 37: ab: c 8: 54: 0 b

doicom

**Comment by shine4chen** [comment]
hi @doicom 
   Currently SONIC doesn't support OSPF configuration. It will be supported future.
   Why do you  want to change port MAC address?  Through you could change port mac address by linux "ip link " cmd , unfortunately linksyncd doesnt listen to mac address change event. So event can't be propagated to sai layer. Chip still uses old mac address.

**Comment by doicom** [comment]
Hi,@shine4chen
Thank you for your reply.

`Currently SONIC doesn't support OSPF configuration. `
Regarding OSPF, we did not check the road map plan carefully.
I'm sorry.

By the way, BGP was described in config_db.json by default.
Does BGP stop functioning when deleted?

`Why do you want to change port MAC address?`
I confirmed it because it can be changed with a general switch.
When I explained to someone, I asked because I was not able to answer whether I can change MAC address.

doicom

**Comment by shine4chen** [comment]
@doicom 
Sure, if  BGP configuration is deleted from config_db.json BGP stop . But bgpcfgd, bgpd and zebra daemon is still running. If you configure bgp by sonic CLI later , bgp would work again.

**Comment by doicom** [comment]
Hi,@shine4chen
Thank you for your reply.

`Sure, if BGP configuration is deleted from config_db.json BGP stop . But bgpcfgd, bgpd and zebra daemon is still running. If you configure bgp by sonic CLI later , bgp would work again.`

I deleted BGP from config_db.json.
The bgpd daemon is running, but BGP is stopped.
Is this recognition wrong?

If no, please tell me how to stop daemons such as BGP.

doicom

**Comment by shine4chen** [comment]
@doicom Sure, It is correct behavior. The process related BGP is still running. But since it has no configuration bgp can't connect to its neighbor.

**Comment by doicom** [comment]
Hi,@shine4chen
**Sorry for the late reply.**

Thank you for your reply.
Thanks to you, the mystery has been resolved.

doicom
