### ISSUE TITLE
when default route is withdrawed, the route is not removed from the asic

### ISSUE THREAD

**Issue by lguohan** [Azure/SONiC#25]
acsadmin@xx:~$ ip route show
default via 10.208.80.1 dev eth0  proto zebra 

127.0.0.1:6379> hgetall ROUTE_TABLE:0.0.0.0/0
1) "nexthop"
2) "10.208.80.1"
3) "ifname"
4) "eth0"

In the asic, default route still points to the previous nexthops.

**Comment by lguohan** [comment]
problem still exists

**Comment by stcheng** [comment]
ACK
