### ISSUE TITLE
Interfaces not added to port channel with error message as [94801.659843] PortChannel0002: Device Ethernet60 is up. Set it down before adding it as a team port.

### ISSUE THREAD

**Issue by chaitanc** [Azure/SONiC#259]
Configured port channel using below JSON setting in config_db.json

"PORTCHANNEL_INTERFACE": {
        "PortChannel0001|": {}
    }, 
    "PORTCHANNEL": {
        "PortChannel0001": {
            "admin_status": "up", 
            "members": [
                "Ethernet60", 
                "Ethernet64"
            ], 
            "mtu": "9100"
        }
    }
When I am trying to check the traffic hashing in LAG I have applied L2 port channel config and did config reload. Observed the below log message on the console

[94801.659843] PortChannel0002: Device Ethernet60 is up. Set it down before adding it as a team port
Flags: A - active, I - inactive, Up - up, Dw - Down, N/A - not available, S - se[94801.835814] PortChannel0002: Device Ethernet64 is up. Set it down before adding it as a team port

As I tried with 2 ports, none of the ports are added to port channel. I did config reload again, now ports are added to port channel.

I tried to reproduce the issue by changing the port channel name to "PortChannel0001", no issue observed. So, with the working configuration, I sent matching traffic and traffic forwarding is fine.

After some time, I did config reload, and observed the same issue. But this time only one port is added to port channel. Not sure why is this happening even though I have not modified the config. I did config reload again now earlier added port is not added (Error message displayed for the Earlier added port) but the other added fine.
[config_db_l2_port_channel_having_issue.log](https://github.com/Azure/SONiC/files/2463451/config_db_l2_port_channel_having_issue.log)
[port_channel_issue_log_10_04_2018.log](https://github.com/Azure/SONiC/files/2463452/port_channel_issue_log_10_04_2018.log)

I have attached all the required logs of my configuration and output of the debug commands provided by you. Please let me know if you need any other info to narrow down the issue.

**Comment by chaitanc** [comment]
We have an work around for this issue, we can configure the port channel and members of port channel using CLI commands. The syntax which we used earlier to add members to port channel is changed. See below for the correct syntax / schema for config_db.json.
    "PORTCHANNEL": {
        "PortChannel001": {
            "admin_status": "up",
            "mtu": "9100"
        }
    },
    "PORTCHANNEL_MEMBER": {
        "PortChannel001|Ethernet44": {},
        "PortChannel001|Ethernet52": {}
  },

**Comment by stcheng** [comment]
thanks! i'll update the schema file shortly
