### ISSUE TITLE
Traffic hashing is not working in Port channel, should we need to do any extra config for hashing to work ??

### ISSUE THREAD

**Issue by chaitanc** [Azure/SONiC#260]
Setup:
====
                                               2 links (Port channel)
                             Intf1 ======= DUT 1 ============= DUT 2 ====== Int 2
Observations:
========
After bringing up the port channel and adding respective ports in to it, sent matching traffic. Observed that traffic is forwarding to destination interface. When I check the interface counters, observed that traffic is forwarding through only one of 2 ports of port channel. Tried to send hashing traffic like incremental source mac or incremental destination mac. Observed that traffic is dropped.

Should we need to do additional configuration for hashing to work ? If so, please let me know. If this is an issue. Please fix this.

Version:
======
SONiC Software Version: SONiC.HEAD.731-673bb65
Distribution: Debian 9.5
Kernel: 4.9.0-7-amd64
Build commit: 673bb65
Build date: Thu Oct  4 12:39:45 UTC 2018
Built by: johnar@jenkins-worker-4

Attachments:
========
Please find the attached file for my configuration.
[config_db_l2_port_channel_having_issue.log](https://github.com/Azure/SONiC/files/2463488/config_db_l2_port_channel_having_issue.log)

**Comment by chaitanc** [comment]
Can any one respond to this issue ?

**Comment by lguohan** [comment]
the hash fields for lag is tcpip 5-tuple, please vary those fields to see traffic load balancing among the two member ports.
