### ISSUE TITLE
KeyError: 'alias' when we try to use "show" command after shut / unshut the interface using config interface [InterfaceName] [shutdown | startup]

### ISSUE THREAD

**Issue by chaitanc** [Azure/SONiC#268]
Observed below error log when I try to use the "show" command after shut / unshut the interface using 

<b>config interface [InterfaceName] [shutdown | startup]</b>

1) After loading latest build, tried to check the interface status using show interface status command. Observed that interface list showing fine.
2) Now shutdown | startup the Ethernet20 interface using config interface Ethernet20 [shutdown | startup] command.
3) Observed that interface status changing as per the provided command.
4) Now tried to see the interface status again, observed below error log

```
root@sonic-testing:/home/admin# show interface status
Traceback (most recent call last):
  File "/usr/bin/show", line 9, in <module>
    load_entry_point('sonic-utilities==1.2', 'console_scripts', 'show')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/show/main.py", line 193, in <module>
    iface_alias_converter = InterfaceAliasConverter()
  File "/usr/lib/python2.7/dist-packages/show/main.py", line 58, in __init__
    self.port_dict[port_name]['alias']):
KeyError: 'alias'

From this point, getting same error log for all show commands. Tried few for reference

root@sonic-testing:/home/admin# show version
Traceback (most recent call last):
  File "/usr/bin/show", line 9, in <module>
    load_entry_point('sonic-utilities==1.2', 'console_scripts', 'show')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/show/main.py", line 193, in <module>
    iface_alias_converter = InterfaceAliasConverter()
  File "/usr/lib/python2.7/dist-packages/show/main.py", line 58, in __init__
    self.port_dict[port_name]['alias']):
KeyError: 'alias'
root@sonic-testing:/home/admin# show acl table
Traceback (most recent call last):
  File "/usr/bin/show", line 9, in <module>
    load_entry_point('sonic-utilities==1.2', 'console_scripts', 'show')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/show/main.py", line 193, in <module>
    iface_alias_converter = InterfaceAliasConverter()
  File "/usr/lib/python2.7/dist-packages/show/main.py", line 58, in __init__
    self.port_dict[port_name]['alias']):
KeyError: 'alias'
root@sonic-testing:/home/admin# show acl rule
Traceback (most recent call last):
  File "/usr/bin/show", line 9, in <module>
    load_entry_point('sonic-utilities==1.2', 'console_scripts', 'show')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/show/main.py", line 193, in <module>
    iface_alias_converter = InterfaceAliasConverter()
  File "/usr/lib/python2.7/dist-packages/show/main.py", line 58, in __init__
    self.port_dict[port_name]['alias']):
KeyError: 'alias'
```

This error log is getting cleared when we do config reload or reboot. This is a blocker, even though we have an workaround which is time consuming.

SONIC Version:
==========
```
root@sonic-testing:/home/admin# show version
SONiC Software Version: SONiC.HEAD.748-dirty-20181021.115113
Distribution: Debian 9.5
Kernel: 4.9.0-7-amd64
Build commit: 5c65c77
Build date: Sun Oct 21 14:57:29 UTC 2018
Built by: johnar@jenkins-worker-3
```

**Comment by jleveque** [comment]
A couple questions:

1. Do the `show` commands work as expected *before* you shutdown/startup the interface?
2. Do you have an `alias` column specified in your port_config.ini file?

P.S. I modified your original post to format the output for easier reading.

**Comment by chaitanc** [comment]
Yes, show command is working fine before shutdown / startup the interface.

Yes, I have alias column in my port_config.ini file, see below snippet of my port_config.ini file.
```
# name          lanes             alias
Ethernet0       29,30,31,32       fortyGigE0/0
Ethernet4       25,26,27,28       fortyGigE0/4
Ethernet8       37,38,39,40       fortyGigE0/8
Ethernet12      33,34,35,36       fortyGigE0/12
Ethernet16      41,42,43,44       fortyGigE0/16
Ethernet20      45,46,47,48       fortyGigE0/20
Ethernet24      5,6,7,8           fortyGigE0/24
Ethernet28      1,2,3,4           fortyGigE0/28
Ethernet32      9,10,11,12        fortyGigE0/32
Ethernet36      13,14,15,16       fortyGigE0/36
Ethernet40      21,22,23,24       fortyGigE0/40
Ethernet44      17,18,19,20       fortyGigE0/44
Ethernet48      49,50,51,52       fortyGigE0/48
Ethernet52      53,54,55,56       fortyGigE0/52
Ethernet56      61,62,63,64       fortyGigE0/56
Ethernet60      57,58,59,60       fortyGigE0/60
Ethernet64      65,66,67,68       fortyGigE0/64
Ethernet68      69,70,71,72       fortyGigE0/68
Ethernet72      77,78,79,80       fortyGigE0/72

```

**Comment by chaitanc** [comment]
I am having this issue on DELL S 6000 device.

**Comment by jleveque** [comment]
Should be fixed with https://github.com/Azure/sonic-utilities/pull/362.

PR open here: https://github.com/Azure/sonic-buildimage/pull/2252  to update the sonic-utilites submodule. Once this PR is merged, please check again and provide your feedback.

**Comment by jleveque** [comment]
@chaitanc: The PR has been merged. Can you please try imaging with a new build from the head of the master branch and confirm this is fixed for you?

**Comment by chaitanc** [comment]
Verified on build:

```
root@sonic-testing:/home/admin#
root@sonic-testing:/home/admin# show version
SONiC Software Version: SONiC.HEAD.778-0b3a885
Distribution: Debian 9.6
Kernel: 4.9.0-7-amd64
Build commit: 0b3a885
Build date: Sun Nov 18 10:29:43 UTC 2018
Built by: johnar@jenkins-worker-3

```

Hence closing the issue.

**Comment by kirankella** [comment]
Though the interface name is invalid, the interface is getting added into the PORT_TABLE in Config DB, with admin status attribute only. Later during show commands when we query the PORT_TABLE it is throwing error on missing alias.

We should prevent adding invalid interface names into the PORT_TABLE during config commands.
The following fix worked. It throws an error to the user prompting to enter a valid interface name.
The callers of the interface_name_to_alias() function should handle the error return value.

==========
--- a/config/main.py
+++ b/config/main.py
@@ -99,7 +99,6 @@ def interface_name_to_alias(interface_name):
         for port_name in natsorted(port_dict.keys()):
             if interface_name == port_name:
                 return port_dict[port_name]['alias']
-        click.echo("Invalid interface {}".format(interface_alias))

     return None

@@ -823,6 +822,10 @@ def startup(ctx):
     config_db = ctx.obj['config_db']
     interface_name = ctx.obj['interface_name']

+    alias = interface_name_to_alias(interface_name)
+    if alias is None:
+        ctx.fail("Enter valid interface name!!")
+
     if interface_name.startswith("Ethernet"):
         config_db.mod_entry("PORT", interface_name, {"admin_status": "up"})
     elif interface_name.startswith("PortChannel"):
@@ -838,6 +841,10 @@ def shutdown(ctx):
     config_db = ctx.obj['config_db']
     interface_name = ctx.obj['interface_name']

+    alias = interface_name_to_alias(interface_name)
+    if alias is None:
+        ctx.fail("Enter valid interface name!!")
+
     if interface_name.startswith("Ethernet"):
         config_db.mod_entry("PORT", interface_name, {"admin_status": "down"})
     elif interface_name.startswith("PortChannel"):
==========

**Comment by kirankella** [comment]
Hi Joe, I am submitting the config prevention fix (error checking) as mentioned above as part of pull request https://github.com/Azure/sonic-utilities/pull/424

**Comment by jleveque** [comment]
Fixed by https://github.com/Azure/sonic-utilities/pull/424
