### ISSUE TITLE
Sonic on AS5812-54x platform

### ISSUE THREAD

**Issue by parulagrawal14** [Azure/SONiC#275]
Hi All,

Is there any ongoing plan or program to port sonic on AS5812-54x platform?. If not, can someone help us what is the right set of document of guidelines to be followed for porting sonic in AS5812-54x other than the one mentioned in the blow link

https://github.com/Azure/SONiC/wiki/Porting-Guide

Regards,
Parul Agrawal.

**Comment by pollyhsu2git** [comment]
@parulagrawal14 
1). Edge-Core AS5812-54X uses Broadcom MAC chip, Trident2+, which is not supported on SONiC currently (Only Trident2 / Tomahawk / Tomahawk 2)
2). For the latest supported list of the Edge-Core device on SONiC, please refer to `https://github.com/Azure/sonic-buildimage/tree/master/device/accton`

**Comment by mipxman** [comment]
Hi Everyone, 

here we have a device and platform files of AS5812-54X :[]( https://github.com/Azure/sonic-buildimage/tree/master/device/accton/x86_64-accton_as5812_54x-r0 )but it isn't work correctly in device ?! only with GLC-T module and 1 Gbps is OK :[ 

did anyone can help me to build a compatible version of SONiC on this Switch ?

**Comment by Str1ker17** [comment]
@parulagrawal14
I have some experience of supporting Trident2+ in SONiC if you are interested

**Comment by daniele-moro** [comment]
@Str1ker17 did you manage to make SONiC working on a Trident2+ switch? I'm currently facing some issues with an AS5812-54x.

**Comment by Str1ker17** [comment]
@daniele-moro Yes. If you are getting an error message in `/var/log/syslog` about unsupported chip, this is a Broadcom SAI "feature" and you need to mimic under Trident2 (bcm56850). You can contact me in Telegram: https://t.me/Str1ker
