### ISSUE TITLE
How can I use VXLAN and SONIC-CLI　?

### ISSUE THREAD

**Issue by doicom** [Azure/SONiC#286]
Hi all,
I'm sorry if the location of the question is wrong.
Someone, please help us.

I checked [Sonic Roadmap Planning] [SONiC.201810]. I think that a new function [VXLAN, CLI framework] has been added.
I downloaded the binary and checked the actual machine.
It was impossible to run VXLAN.

**### question**
①What is the command to set vxlan?

② I see the command by referring to the following URL.
Is that wrong?

[VXLAN]
https://github.com/Azure/SONiC/pull/240/commits/f85f2b178743343b2c26d0a3e21392bdaae9745f?short_path=64cf713#diff-64cf71344ca20a0e313146b5fb3989de

[SONiC-CLI]
https://github.com/Azure/SONiC/pull/205/commits/4248d53d6f8060334e4b6cfc2b5e423e0958934b?short_path=80d33f2#diff-80d33f29c44d081b650225c9488e339e

③ Do I need to create a binary by myself when using the new function?
⇒ If yes, what would the branch specify?

```
admin@sonic:~$ show version
SONiC Software Version: SONiC.HEAD.771-41702e7
Distribution: Debian 9.6
Kernel: 4.9.0-7-amd64
Build commit: 41702e7
Build date: Tue Nov 13 01:30:38 UTC 2018
Built by: johnar@jenkins-worker-4

Docker images:
REPOSITORY                 TAG                 IMAGE ID            SIZE
docker-syncd-brcm          HEAD.771-41702e7    e609cbfe1368        336.9 MB
docker-syncd-brcm          latest              e609cbfe1368        336.9 MB
docker-orchagent-brcm      HEAD.771-41702e7    bc287359dfa2        283.3 MB
docker-orchagent-brcm      latest              bc287359dfa2        283.3 MB
docker-lldp-sv2            HEAD.771-41702e7    23fcbc47fd12        271.7 MB
docker-lldp-sv2            latest              23fcbc47fd12        271.7 MB
docker-dhcp-relay          HEAD.771-41702e7    d682349406ef        253.9 MB
docker-dhcp-relay          latest              d682349406ef        253.9 MB
docker-database            HEAD.771-41702e7    f57d57802690        252.6 MB
docker-database            latest              f57d57802690        252.6 MB
docker-teamd               HEAD.771-41702e7    c21c3caaeeb2        271.5 MB
docker-teamd               latest              c21c3caaeeb2        271.5 MB
docker-snmp-sv2            HEAD.771-41702e7    db506e75ad87        291.4 MB
docker-snmp-sv2            latest              db506e75ad87        291.4 MB
docker-router-advertiser   HEAD.771-41702e7    8d8b024059fd        250.2 MB
docker-router-advertiser   latest              8d8b024059fd        250.2 MB
docker-platform-monitor    HEAD.771-41702e7    7866e8166217        284.1 MB
docker-platform-monitor    latest              7866e8166217        284.1 MB
docker-fpm-quagga          HEAD.771-41702e7    3403c6ee6641        278.3 MB
docker-fpm-quagga          latest              3403c6ee6641        278.3 MB
```

doicom

**Comment by prsunny** [comment]
@doicom , the Vxlan work is in-progress. Some PRs are not yet merged. CLI would be in phase2.

**Comment by doicom** [comment]
Hi,@prsunny 
Thank you for your reply.

`the Vxlan work is in-progress.`
When will Vxlan be available?

`Some PRs have not yet been merged.`

I could not judge the merge location.
Where is the place to check the merged part?

doicom

**Comment by sajishv** [comment]
Hi, 

Please let me know if VxLAN support is enabled in the latest master branch. 
Also, can you let me know what level of support is currently available. 

Thanks,
Sajish.
