### ISSUE TITLE
Question: Clarification on EVPN Type 2,3 & 5 route.

### ISSUE THREAD

**Issue by jcmathews** [Azure/SONiC#337]
Does FRR BGP EVPN send the type 2, type 3 and type 5 updates to SONIC NetDispatcher->NeighSync (Where Neighbor Additions are done in NEIGH_TABLE) ?
Reference HEAD

**Comment by nikos-github** [comment]
Not yet. SONiC hasn't been modified yet for evpn support.

**Comment by jcmathews** [comment]
But looks like the Frr BGP is installing the route(Say type 3) via zebra (zvni_vtep_install -> kernel_add_vtep->netlink_vxlan_flood_list_update->netlink(RTM_NEWNEIGH))
On SONIC side NetDispatcher is registered for RTM_NEWNEIGH. This should ideally receive the neighbor addition notification, where NeighSync will put into APP_NEIGH_TABLE. Rest is mystery

**Comment by prsunny** [comment]
@baiwei0427, can you check?
