### ISSUE TITLE
Question: VXLAN Bridging support.

### ISSUE THREAD

**Issue by jcmathews** [Azure/SONiC#338]
@prsunny : I do see some code changes which were missing before (as //BRIDGE handling) are available in vNetOrch::addOperartion() which creates vNetBitmap Objects. However not seen not seen tunnel map creation in this context like VRF case. 
Could you please help on the below queries
1) Is bridge support available on git latest in VXLAN context?
2) Does SAI supports VXLAN Bridging. 
3) Does SONIC has replication logic for the peer_list populated for a VNI as well as SAI?

Also could you please share the VXLAN HLD/pointers if it describes about some of the above queries?

**Comment by prsunny** [comment]
The BitMap implementation is specific to Mellanox platform and not for the L2 Vxlan
1. Not yet. 
2. Expect to support but not yet verified
3. Replication logic is in orchagent. However there are platform optimizations for the replication logic w.r.t resource utilizations in SAI.

The document that is currently available is the Vxlan [HLD](https://github.com/Azure/SONiC/blob/master/doc/vxlan/Vxlan_hld.md).

**Comment by jcmathews** [comment]
@prsunny 
1. Is l2vxlan (Bridge support ) planned for upcoming release in march? 
2. Could you please give some pointers on bridge support implementation for understanding. Can it be mapped with BitMap implementation where the SAI_TABLE_BITMAP** is to be accommodated with SAI_BRIDGE** related api? 
3. Could you please some pointers on broadcom related replication logic.

**Comment by prsunny** [comment]
1. Planning is in progress for l2vxlan and shall be updated in Roadmap page. 
2. I don't have a documentation for it now. I don't think you can map those two APIs. 
3. As I mentioned, replication logic is in orchagent. You would want to look at 
bool VNetRouteOrch::doRouteTask<VNetVrfObject> - line 1224 where it replicates routes to peer Vnets.

**Comment by jcmathews** [comment]
3. Does it mean that HER is supported?
