### ISSUE TITLE
Question : Clarification on ARP in SONIC.

### ISSUE THREAD

**Issue by jcmathews** [Azure/SONiC#339]
@prsunny :
Could you please let me know how the ARP/APP_NEIGH_TABLE population is done in SONIC as well as in ASIC when a host connects, w.r.t SONIC/Broadcom context for understanding.

My guess are
1) ARP requests are to be lifted to CPU via netdev to Linux kernel and once the entry is installed in linux the entries are passed to SONIC APP_NEIGH_TABLE and to ASIC DB
2) ASIC learns and populates ASIC ARP_TABLE, then this is synced via syncd to ASIC DB to APP_TABLE to Linux.

Not clear about how this happens. Sorry if above points are misleading.

**Comment by prsunny** [comment]
ARP learning happens as mentioned in 1 above. 2 is essentially FDB/MAC learning.
