### ISSUE TITLE
pmon enhancement suggestion

### ISSUE THREAD

**Issue by richard28530** [Azure/SONiC#385]
As detail in pmon-enhancement-design.md, the psu state db schema is define as below.

But sometimes we may want know the power supply detailed information.

can we add input/output voltage and current to the state db ?
@keboliu 

<pre>
; Defines information for a psu
key                     = PSU_INFO|psu_name              ; information for the psu
; field                 = value
presence                = BOOLEAN                        ; presence of the psu     
model                   = STRING                         ; model name of the psu
serial                  = STRING                         ; serial number of the psu
status                  = BOOLEAN                        ; status of the psu
change_event            = STRING                         ; change event of the psu
fan                     = STRING                         ; fan_name of the psu
led_status              = STRING                         ; led status of the psu
</pre>

**Comment by keboliu** [comment]
@richard28530 I am OK for adding new PSU entries to DB, in the new platform API there is some API defined to get the voltage of PSU,https://github.com/Azure/sonic-platform-common/blob/master/sonic_platform_base/psu_base.py#L68  you can do it based on the new API and even suggest new APIs if you feel necessary.

**Comment by richard28530** [comment]
Glad to hear that.
