### ISSUE TITLE
Pre-ARP support for static route config

### ISSUE THREAD

**Issue by xzmalfred** [Azure/SONiC#387]
In our testing we found that SONIC currently doesn't handle a basic static route case properly. 
A test case is like: 

Spirent port 1--[192.168.11.0/24]---Sonic1--[192.168.12.0/24]--Sonic2--[192.168.13.0/24]---Spirent port 2 

Bidirection L3 traffic is sent from  Spirent port1 (192.168.11.2) to  Spirent port2 (192.168.13.2). Static routes are configured on both Sonic1 and Sonic2.  

On Sonic1, traffic received from Spirent port1 is not getting forwarded towards Sonic2 and vice versa. On Sonic1, ARP table does not have entry for next hop i.e 192.168.12.2 ip of Sonic2, and the traffic is transit only so no cpu traffic generated to learn ARP of 192.168.12.2

Has this issue been discussed in SONIC community before? is this static route test case not-supported? Orchagent currently doesn't program this static route in hardware as its next hop is not resolved. As a result the traffic will hit default route which is drop.
To workaround this in SONIC, we need to first generate cpu bound traffic to resolve the ARP before the transit traffic can be forwarded.   
In other router implementation, application may call linux kernel to send ARP request in order to resolve the next hop.  this is so called a "pre-arp".  We would like to hear community members' thoughts.

**Comment by prsunny** [comment]
This is a known issue. Sonic currently doesn't support adding static route for which nexthop is not resolved.

**Comment by xzmalfred** [comment]
Thanks for the reply, Prince. Any thoughts on the approach how to fix it? IMO a complete solution may be adding the pre-arp agent to maintain the states and request kernel to resolve ARPs when needed. I'd like to hear your thoughts

**Comment by prsunny** [comment]
There is already agent to resolve ARP based on request. May be you can leverage that. https://github.com/Azure/sonic-swss/blob/master/doc/swss-schema.md#neigh_table-1

Note that `mac-address` field is optional!

**Comment by xzmalfred** [comment]
yes I see that part of reservation but the schema doesn't include any design of the "agent". so there is no agent yet, or am I missing anything?

**Comment by prsunny** [comment]
There is already. That is handled by `nbrmgr`. I send the schema for your reference. You can add an entry to configDB as in schema and check behavior.

**Comment by anshuv-mfst** [comment]
@xzmalfred - could you please re-test and close if the issue is no longer seen, Thanks.

**Comment by anshuv-mfst** [comment]
Please re-open if issue is seen.
