### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by Alonzzzo2** [Azure/SONiC#396]
some documentation issues I encountered while reading the architecture document, hope I'm doing it (creating the case) right:

at:
https://github.com/Azure/SONiC/wiki/Architecture

1. spelling: process and **massage** this information 
2. spelling: STATE_DB to get a **life**-feed of the 
3. diagram legend: SNMP-state interactions. - the steps described are starting with index 1 and not 0 as in the diagram
4. spelling: the routing **-tate** held within zebra
5. diagram legend: Routing-state interactions. - again, offset between the diagram's states and the steps descriptions
6. diagram legend: Port-state interactions. - offset, again
7. spelling: Let's **know** iterate through the sequence
8. diagram legend: "Let's know iterate through the sequence of steps that take place when a physical port goes down:" - offset again

**Comment by stcheng** [comment]
@Alonzzzo2 Thanks. I've fixed these issues.
