### ISSUE TITLE
Repository not opened

### ISSUE THREAD

**Issue by baloo** [Azure/SONiC#4]
Hi,

An issue, just to notify you a bunch of repositories among the list in https://github.com/Azure/SONiC/blob/gh-pages/sourcecode.md are not yet opened to the public.

Thanks for opening sonic!

**Comment by dplore** [comment]
Thanks!  I have corrected the issues.  There was a typo in swss and the sonic-mgmt example configuration is not ready yet.  We’re working to get that released soon.

-Darren

**Comment by anomaly256** [comment]
There are other broken links still, for example I was particularly interested in checking out https://github.com/Azure/sonic-linux-kernel but it 404s

**Comment by Lewiscowles1986** [comment]
it's just sairedis now. Thanks for staying on top of this, and opening this project. I checked all the links to projects in #6

**Comment by dplore** [comment]
No problem.   sairedis is ‘not ready’ for it’s initial commit to the public.  We hope to have this resolved in a few days.  THanks for the pull request, I’ll check it out.

-Darren

**Comment by Lewiscowles1986** [comment]
:+1: Thanks for the involvement, I do really appreciate it.
