### ISSUE TITLE
How to breakout a port

### ISSUE THREAD

**Issue by ifconf1g** [Azure/SONiC#412]
Hi All

I am trying  breakout a port 1x40 to 4x10  ,like in this guide https://github.com/Azure/SONiC/wiki/How-to-breakout-a-port  but unfortunately after port_config.ini  change ,all ports goes down. 
Is there a way to solve this issue?

I'm running the following build:
Platform: x86_64-accton_as6712_32x-r0
HwSKU: Accton-AS6712-32X
ASIC: broadcom

SONiC Software Version: SONiC.201904.0-23fb00c
Distribution: Debian 9.9
Kernel: 4.9.0-8-2-amd64
Build commit: 23fb00c

port_config.ini
![Screenshot from 2019-06-27 16-48-56](https://user-images.githubusercontent.com/50233228/60269337-53b58c00-98ff-11e9-94e8-88d6ca4e51ec.png)

![Screenshot from 2019-06-27 16-54-32](https://user-images.githubusercontent.com/50233228/60269360-60d27b00-98ff-11e9-93c9-ce7052c31d27.png)

Interfaces status
![Screenshot from 2019-06-27 17-01-07](https://user-images.githubusercontent.com/50233228/60269388-6af47980-98ff-11e9-985d-674c22996648.png)

Thanks

**Comment by pawelmaslanka** [comment]
@ifconf1g ,

I would suggest you to check _config.bcm_ file for your HwSKU whether it reflects your profile with splitted ports.

Hope it help
