### ISSUE TITLE
BGP L2VPN EVPN + VXLAN

### ISSUE THREAD

**Issue by ehsnsbn** [Azure/SONiC#416]
hello dear experts,

sorry for my simple question, as I am pretty new to SONIC AZURE.
if we install sonic azure on our whitebox  switch, can we implement VXLAN + BGP L2VPN EVPN solution in a data center CLOS network?

thank you for your support! :)

**Comment by prsunny** [comment]
This development is in progress and expected by next quarter. Currently L2VPN is not supported.
