### ISSUE TITLE
Compile error while building debian stretch required targets

### ISSUE THREAD

**Issue by icecreamkuan** [Azure/SONiC#417]
I came across a problem while executing command "BLDENV=stretch make stretch",
i think this error may occurred when dpkg installing frr_7.0.1-sonic-0_amd64.deb,
and it's failing with the following message:
```
[ 01 ] [ target/debs/stretch/libnl-3-200_3.2.27-2_amd64.deb-install ]
[ 01 ] [ target/debs/stretch/libnl-3-dev_3.2.27-2_amd64.deb-install ]
[ 01 ] [ target/debs/stretch/libsnmp-base_5.7.3+dfsg-1.5_all.deb-install ]
[ 01 ] [ target/debs/stretch/libsnmp30_5.7.3+dfsg-1.5_amd64.deb-install ]
[ 01 ] [ target/debs/stretch/libsnmp-dev_5.7.3+dfsg-1.5_amd64.deb-install ]
[ 01 ] [ target/debs/stretch/swig3.0_3.0.12-2_amd64.deb-install ]
[ 01 ] [ target/debs/stretch/swig_3.0.12-2_amd64.deb-install ]
[ 01 ] [ target/debs/stretch/libyang0.16_0.16.105-1_amd64.deb-install ]
[ 01 ] [ target/debs/stretch/libyang-dev_0.16.105-1_amd64.deb-install ]
[ FAIL LOG START ] [ target/debs/stretch/frr_7.0.1-sonic-0_amd64.deb ]
make[1]: Entering directory '/sonic/src/sonic-frr'
# Build the package
pushd ./frr
tools/tarsource.sh -V -e '-sonic'
dpkg-buildpackage -rfakeroot -b -us -uc -Ppkg.frr.nortrlib -j1
popd
mv frr-pythontools_7.0.1-sonic-0_all.deb frr-dbgsym_7.0.1-sonic-0_amd64.deb frr_7.0.1-sonic-0_amd64.deb /sonic/target/debs/stretch/
/sonic/src/sonic-frr/frr /sonic/src/sonic-frr
fatal: Not a git repository: /home/kuan/SONIC/sonic-buildimage/.git/modules/src/sonic-frr/frr

failed

please try running the script without the -d option.
Makefile:9: recipe for target '/sonic/target/debs/stretch/frr_7.0.1-sonic-0_amd64.deb' failed
make[1]: *** [/sonic/target/debs/stretch/frr_7.0.1-sonic-0_amd64.deb] Error 128
make[1]: Leaving directory '/sonic/src/sonic-frr'
[  FAIL LOG END  ] [ target/debs/stretch/frr_7.0.1-sonic-0_amd64.deb ]
slave.mk:285: recipe for target 'target/debs/stretch/frr_7.0.1-sonic-0_amd64.deb' failed
make: *** [target/debs/stretch/frr_7.0.1-sonic-0_amd64.deb] Error 1
make[1]: *** [stretch] Error 2
make[1]: Leaving directory `/home/kuan/SONIC/sonic-buildimage'
make: *** [stretch] Error 2
```
My compile environment:
```
Ubuntu 14.04.6 LTS
GNU Make 3.81
```

**Comment by jleveque** [comment]
Did you run `make init` first? Instructions for building can be found at https://github.com/Azure/sonic-buildimage/blob/master/README.md.

**Comment by prsunny** [comment]
I faced it few days back and one suggestion is to remove the sonic-frr/frr folder, do make init and compile again.

**Comment by icecreamkuan** [comment]
Yes, i have already run `make init`,
i think this issue may caused by my compile environment,
so i upgraded my Ubuntu version, remove source code and do git-clone and compile again,
then `BLDENV=stretch make stretch` was completed successfully.

New compile environment:
```
Ubuntu 16.04.6 LTS
GNU Make 4.1
```

**Comment by SoftPaper** [comment]
[ FAIL LOG START ] [ target/debs/stretch/libsai_1.3.3_amd64.deb-install ]
dpkg-deb: error: 'target/debs/stretch/libsai_1.3.3_amd64.deb' is not a debian format archive
dpkg: error processing archive target/debs/stretch/libsai_1.3.3_amd64.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2
Errors were encountered while processing:
 target/debs/stretch/libsai_1.3.3_amd64.deb
[  FAIL LOG END  ] [ target/debs/stretch/libsai_1.3.3_amd64.deb-install ]
slave.mk:410: recipe for target 'target/debs/stretch/libsai_1.3.3_amd64.deb-install' failed
make: *** [target/debs/stretch/libsai_1.3.3_amd64.deb-install] Error 1
Makefile.work:201: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/sonic/sonic-buildimage'
Makefile:6: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by SoftPaper** [comment]
> [ FAIL LOG START ] [ target/debs/stretch/libsai_1.3.3_amd64.deb-install ]
> dpkg-deb: error: 'target/debs/stretch/libsai_1.3.3_amd64.deb' is not a debian format archive
> dpkg: error processing archive target/debs/stretch/libsai_1.3.3_amd64.deb (--install):
> subprocess dpkg-deb --control returned error exit status 2
> Errors were encountered while processing:
> target/debs/stretch/libsai_1.3.3_amd64.deb
> [ FAIL LOG END ] [ target/debs/stretch/libsai_1.3.3_amd64.deb-install ]
> slave.mk:410: recipe for target 'target/debs/stretch/libsai_1.3.3_amd64.deb-install' failed
> make: *** [target/debs/stretch/libsai_1.3.3_amd64.deb-install] Error 1
> Makefile.work:201: recipe for target 'all' failed
> make[1]: *** [all] Error 2
> make[1]: Leaving directory '/home/sonic/sonic-buildimage'
> Makefile:6: recipe for target 'all' failed
> make: *** [all] Error 2


怎么解决这个问题

How to solve this problem？
