### ISSUE TITLE
Accton AS5812-54X  run SONiC  failed

### ISSUE THREAD

**Issue by ZhengMinxian** [Azure/SONiC#444]
Since as5812-54x platform   is added to the branch  : https://github.com/Azure/sonic-buildimage/commit/4d212debc7a646ffa61cca767e18d882daadb51d

So I try to run lastest SONiC software on AS5812-54X  . But after the boot ,only **6** docker containers are running  ，5 containers  are not  running correctly    :
![image](https://user-images.githubusercontent.com/22835075/63338598-ad718a00-c375-11e9-9633-2b5c12946f23.png)
Under normal circumstances , there are 11 containers.

admin@sonic:~$ **show version**
SONiC Software Version: SONiC.HEAD.65-dirty-20190820.071834
Distribution: Debian 9.9
Kernel: 4.9.0-9-2-amd64
Build commit: 8facac91
Build date: Tue Aug 20 07:29:26 UTC 2019
Built by: johnar@jenkins-worker-3

Platform: x86_64-accton_as5812_54x-r0
HwSKU: Accton-AS5812-54X
ASIC: broadcom
Serial Number: 581254X1742055
Uptime: 09:12:16 up 12 min,  2 users,  load average: 0.00, 0.48, 0.61

Docker images:
REPOSITORY                 TAG                             IMAGE ID            SIZE
docker-syncd-brcm          HEAD.65-dirty-20190820.071834   1a0fbf72621e        392MB
docker-syncd-brcm          latest                          1a0fbf72621e        392MB
docker-lldp-sv2            HEAD.65-dirty-20190820.071834   c60f807093ec        298MB
docker-lldp-sv2            latest                          c60f807093ec        298MB
docker-router-advertiser   HEAD.65-dirty-20190820.071834   535e23ff5cb0        281MB
docker-router-advertiser   latest                          535e23ff5cb0        281MB
docker-dhcp-relay          HEAD.65-dirty-20190820.071834   4f95737c1a39        289MB
docker-dhcp-relay          latest                          4f95737c1a39        289MB
docker-database            HEAD.65-dirty-20190820.071834   dbf106c875be        281MB
docker-database            latest                          dbf106c875be        281MB
docker-teamd               HEAD.65-dirty-20190820.071834   6c3eb4eb6c37        302MB
docker-teamd               latest                          6c3eb4eb6c37        302MB
docker-snmp-sv2            HEAD.65-dirty-20190820.071834   5a34545c9b30        323MB
docker-snmp-sv2            latest                          5a34545c9b30        323MB
docker-orchagent           HEAD.65-dirty-20190820.071834   b752ccb1a190        321MB
docker-orchagent           latest                          b752ccb1a190        321MB
docker-fpm-frr             HEAD.65-dirty-20190820.071834   508a5b43c8eb        319MB
docker-fpm-frr             latest                          508a5b43c8eb        319MB
docker-sonic-telemetry     HEAD.65-dirty-20190820.071834   6028cdc66869        304MB
docker-sonic-telemetry     latest                          6028cdc66869        304MB
docker-platform-monitor    HEAD.65-dirty-20190820.071834   ccd94cde45bd        326MB
docker-platform-monitor    latest                          ccd94cde45bd        326MB

**sudo generate_dump** :
[sonic_dump_sonic_20190820_091320.tar.gz](https://github.com/Azure/SONiC/files/3519968/sonic_dump_sonic_20190820_091320.tar.gz)

**Comment by ZhengMinxian** [comment]
5812 is not a supported  platform  in   list of the Edge-Core devices . https://github.com/Azure/sonic-buildimage/tree/master/device/accton

**Comment by axyakshay** [comment]
> 5812 is not a supported platform in list of the Edge-Core devices . https://github.com/Azure/sonic-buildimage/tree/master/device/accton

@ZhengMinxian I still face the same issue .I 'm using Oct build and all docker containers do not come up 
`root@sonic:/home/admin# docker ps
CONTAINER ID        IMAGE                            COMMAND                  CREATED             STATUS              PORTS               NAMES
0d6ec000a6d9        docker-dhcp-relay:latest         "/usr/bin/docker_ini…"   25 minutes ago      Up 2 seconds                            dhcp_relay
34362bea6616        docker-syncd-brcm:latest         "/usr/bin/supervisord"   25 minutes ago      Up 10 seconds                           syncd
bb0a7775ef50        docker-teamd:latest              "/usr/bin/supervisord"   26 minutes ago      Up 13 seconds                           teamd
eb717f22c762        docker-snmp-sv2:latest           "/usr/bin/supervisord"   26 minutes ago      Up 14 seconds                           snmp
1638ebe58a1f        docker-orchagent:latest          "/usr/bin/supervisord"   26 minutes ago      Up 22 seconds                           swss
021ec996b5f6        docker-fpm-frr:latest            "/bin/sh -c '/usr/bi…"   26 minutes ago      Up 3 minutes                            bgp
9baedf1b29fc        docker-platform-monitor:latest   "/usr/bin/docker_ini…"   26 minutes ago      Up 3 minutes                            pmon
2e2ec484d2b8        docker-lldp-sv2:latest           "/usr/bin/supervisord"   26 minutes ago      Up 2 minutes                            lldp
df7bb14b97f7        docker-sonic-telemetry:latest    "/usr/bin/supervisord"   26 minutes ago      Up 26 minutes                           telemetry
5247cac417e4        docker-database:latest           "/usr/local/bin/dock…"   26 minutes ago      Up 26 minutes                           database
root@sonic:/home/admin# show interfaces transceiver presence
Traceback (most recent call last):
  File "/usr/bin/sfpshow", line 358, in <module>
    cli()
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/bin/sfpshow", line 355, in presence
    sfp.display_presence(port)
  File "/usr/bin/sfpshow", line 324, in display_presence
    for i in port_table_keys:
TypeError: 'NoneType' object is not iterable
root@sonic:/home/admin# docker ps
CONTAINER ID        IMAGE                            COMMAND                  CREATED             STATUS              PORTS               NAMES
eb717f22c762        docker-snmp-sv2:latest           "/usr/bin/supervisord"   26 minutes ago      Up About a minute                       snmp
021ec996b5f6        docker-fpm-frr:latest            "/bin/sh -c '/usr/bi…"   27 minutes ago      Up 4 minutes                            bgp
9baedf1b29fc        docker-platform-monitor:latest   "/usr/bin/docker_ini…"   27 minutes ago      Up 4 minutes                            pmon
2e2ec484d2b8        docker-lldp-sv2:latest           "/usr/bin/supervisord"   27 minutes ago      Up 3 minutes                            lldp
df7bb14b97f7        docker-sonic-telemetry:latest    "/usr/bin/supervisord"   27 minutes ago      Up 27 minutes                           telemetry
5247cac417e4        docker-database:latest           "/usr/local/bin/dock…"   27 minutes ago      Up 27 minutes                           database
root@sonic:/home/admin# docker ps
CONTAINER ID        IMAGE                            COMMAND                  CREATED             STATUS              PORTS               NAMES
bb0a7775ef50        docker-teamd:latest              "/usr/bin/supervisord"   28 minutes ago      Up About a minute                       teamd
021ec996b5f6        docker-fpm-frr:latest            "/bin/sh -c '/usr/bi…"   28 minutes ago      Up 5 minutes                            bgp
9baedf1b29fc        docker-platform-monitor:latest   "/usr/bin/docker_ini…"   28 minutes ago      Up 5 minutes                            pmon
2e2ec484d2b8        docker-lldp-sv2:latest           "/usr/bin/supervisord"   28 minutes ago      Up 5 minutes                            lldp
df7bb14b97f7        docker-sonic-telemetry:latest    "/usr/bin/supervisord"   28 minutes ago      Up 28 minutes                           telemetry
5247cac417e4        docker-database:latest           "/usr/local/bin/dock…"   29 minutes ago      Up 29 minutes                           database`
