### ISSUE TITLE
Barefoot/SONiC 201811 tcpdump no traffic

### ISSUE THREAD

**Issue by tim-rj** [Azure/SONiC#473]
I try to tcpdump the RDMA traffice in SONiC with command as follows:
tcpdump -i Ethernet0 -w target.cap
the OFED command used the ib_write_bw
However, I get zero traffic with tcpdump in SONiC: 

The "show version" show:
SONiC Software Version: SONiC.HEAD.0-dirty-20181120.090735
Distribution: Debian 8.11
Kernel: 3.16.0-5-amd64
Build commit: 5011622
Build date: Tue Nov 20 09:21:07 UTC 2018
Built by: rj@rj-RG-RCD6000-Office

The " show platform summary" show:
Platform: x86_64-ruijie_s6500_32cq-r0
HwSKU: rj
ASIC: barefoot

**Comment by keboliu** [comment]
is the RDMA traffic you mentioned supposed to be trapped to CPU?

**Comment by tim-rj** [comment]
@keboliu i only know the CPU is working at high performance model with maximum HZ

**Comment by tim-rj** [comment]
it is a mistake. close it please.
