### ISSUE TITLE
portchannel does not come up on Aurora 420

### ISSUE THREAD

**Issue by ehsnsbn** [Azure/SONiC#474]
hello dear experts,
we have sonic on netberg aurora 420 via following porting guide.
the L3 communication among two devices are fine. the BGP session comes up.
now we want to configure portchannel001 over Ethernet2, Ethernet3 among these two devices (both of them are Aurora 420); however, the portchannel does not come up.
would you please help me with this regard?
thank you!

root@device:~# teamshow
Flags: A - active, I - inactive, Up - up, Dw - Down, N/A - not available,
       S - selected, D - deselected, * - not synced
  No.  Team Dev        Protocol     Ports
-----  --------------  -----------  -------------------------
  001  PortChannel001  LACP(A)(Dw)  Ethernet2(D) Ethernet3(D)

root@device:~# show interfaces status
     Interface    Lanes    Speed    MTU          Alias            Vlan    Oper    Admin            Type    Asym PFC
--------------  -------  -------  -----  -------------  --------------  ------  -------  --------------  ----------
     Ethernet0       13       1G   9100       oneGigE1          routed    down       up             N/A         N/A
     Ethernet1       14       1G   9100       oneGigE2          routed    down       up             N/A         N/A
     Ethernet2       15       1G   9100       oneGigE3  PortChannel001      up       up  SFP/SFP+/SFP28         N/A
     Ethernet3       16       1G   9100       oneGigE4  PortChannel001      up       up  SFP/SFP+/SFP28         N/A
     Ethernet4       21      10G   9100       tenGigE5          routed    down       up             N/A         N/A
     Ethernet5       22      10G   9100       tenGigE6          routed    down       up             N/A         N/A
     Ethernet6       23      10G   9100       tenGigE7          routed    down       up             N/A         N/A
     Ethernet7       24      10G   9100       tenGigE8          routed    down       up             N/A         N/A
     Ethernet8       25      10G   9100       tenGigE9          routed    down       up             N/A         N/A
     Ethernet9       26      10G   9100      tenGigE10          routed    down       up             N/A         N/A
    Ethernet10       27      10G   9100      tenGigE11          routed    down       up             N/A         N/A
    Ethernet11       28      10G   9100      tenGigE12          routed    down       up             N/A         N/A
    Ethernet12       29      10G   9100      tenGigE13          routed    down       up             N/A         N/A
    Ethernet13       30      10G   9100      tenGigE14          routed    down       up             N/A         N/A
    Ethernet14       31      10G   9100      tenGigE15          routed    down       up             N/A         N/A
    Ethernet15       32      10G   9100      tenGigE16          routed    down       up             N/A         N/A
    Ethernet16       45      10G   9100      tenGigE17          routed    down       up             N/A         N/A
    Ethernet17       46      10G   9100      tenGigE18          routed    down       up             N/A         N/A
    Ethernet18       47      10G   9100      tenGigE19          routed    down       up             N/A         N/A
    Ethernet19       48      10G   9100      tenGigE20          routed    down       up             N/A         N/A
    Ethernet20       49      10G   9100      tenGigE21          routed    down       up             N/A         N/A
    Ethernet21       50      10G   9100      tenGigE22          routed    down       up             N/A         N/A
    Ethernet22       51      10G   9100      tenGigE23          routed    down       up             N/A         N/A
    Ethernet23       52      10G   9100      tenGigE24          routed    down       up             N/A         N/A
    Ethernet24       53      10G   9100      tenGigE25          routed    down       up             N/A         N/A
    Ethernet25       54      10G   9100      tenGigE26          routed    down       up             N/A         N/A
    Ethernet26       55      10G   9100      tenGigE27          routed    down       up             N/A         N/A
    Ethernet27       56      10G   9100      tenGigE28          routed    down       up             N/A         N/A
    Ethernet28       57      10G   9100      tenGigE29          routed    down       up             N/A         N/A
    Ethernet29       58      10G   9100      tenGigE30          routed    down       up             N/A         N/A
    Ethernet30       59      10G   9100      tenGigE31          routed    down       up             N/A         N/A
    Ethernet31       60      10G   9100      tenGigE32          routed    down       up             N/A         N/A
    Ethernet32       61      10G   9100      tenGigE33          routed    down       up             N/A         N/A
    Ethernet33       62      10G   9100      tenGigE34          routed    down       up             N/A         N/A
    Ethernet34       63      10G   9100      tenGigE35          routed    down       up             N/A         N/A
    Ethernet35       64      10G   9100      tenGigE36          routed    down       up             N/A         N/A
    Ethernet36       65      10G   9100      tenGigE37          routed    down       up             N/A         N/A
    Ethernet37       66      10G   9100      tenGigE38          routed    down       up             N/A         N/A
    Ethernet38       67      10G   9100      tenGigE39          routed    down       up             N/A         N/A
    Ethernet39       68      10G   9100      tenGigE40          routed    down       up             N/A         N/A
    Ethernet40       69      10G   9100      tenGigE41          routed    down       up             N/A         N/A
    Ethernet41       70      10G   9100      tenGigE42          routed    down       up             N/A         N/A
    Ethernet42       71      10G   9100      tenGigE43          routed    down       up             N/A         N/A
    Ethernet43       72      10G   9100      tenGigE44          routed    down       up             N/A         N/A
    Ethernet44       73      10G   9100      tenGigE45          routed    down       up             N/A         N/A
    Ethernet45       74      10G   9100      tenGigE46          routed    down       up             N/A         N/A
    Ethernet46       75      10G   9100      tenGigE47          routed    down       up             N/A         N/A
    Ethernet47       76      10G   9100      tenGigE48          routed    down       up             N/A         N/A
    Ethernet48       77      10G   9100  fortyGigE49/0          routed    down       up             N/A         N/A
    Ethernet49       78      10G   9100  fortyGigE49/1          routed    down       up             N/A         N/A
    Ethernet50       79      10G   9100  fortyGigE49/2          routed    down       up             N/A         N/A
    Ethernet51       80      10G   9100  fortyGigE49/3          routed    down       up             N/A         N/A
    Ethernet52       81      10G   9100  fortyGigE50/0          routed    down       up             N/A         N/A
    Ethernet53       82      10G   9100  fortyGigE50/1          routed    down       up             N/A         N/A
    Ethernet54       83      10G   9100  fortyGigE50/2          routed    down       up             N/A         N/A
    Ethernet55       84      10G   9100  fortyGigE50/3          routed    down       up             N/A         N/A
    Ethernet56       97      10G   9100  fortyGigE51/0          routed    down       up             N/A         N/A
    Ethernet57       98      10G   9100  fortyGigE51/1          routed    down       up             N/A         N/A
    Ethernet58       99      10G   9100  fortyGigE51/2          routed    down       up             N/A         N/A
    Ethernet59      100      10G   9100  fortyGigE51/3          routed    down       up             N/A         N/A
    Ethernet60      101      10G   9100  fortyGigE52/0          routed    down       up             N/A         N/A
    Ethernet61      102      10G   9100  fortyGigE52/1          routed    down       up             N/A         N/A
    Ethernet62      103      10G   9100  fortyGigE52/2          routed    down       up             N/A         N/A
    Ethernet63      104      10G   9100  fortyGigE52/3          routed    down       up             N/A         N/A
    Ethernet64      105      10G   9100  fortyGigE53/0          routed    down       up             N/A         N/A
    Ethernet65      106      10G   9100  fortyGigE53/1          routed    down       up             N/A         N/A
    Ethernet66      107      10G   9100  fortyGigE53/2          routed    down       up             N/A         N/A
    Ethernet67      108      10G   9100  fortyGigE53/3          routed    down       up             N/A         N/A
    Ethernet68      109      10G   9100  fortyGigE54/0          routed    down       up             N/A         N/A
    Ethernet69      110      10G   9100  fortyGigE54/1          routed    down       up             N/A         N/A
    Ethernet70      111      10G   9100  fortyGigE54/2          routed    down       up             N/A         N/A
    Ethernet71      112      10G   9100  fortyGigE54/3          routed    down       up             N/A         N/A
PortChannel001      N/A       2G   9100            N/A          routed    down       up             N/A         N/A

[config_db_json.txt](https://github.com/Azure/SONiC/files/3666559/config_db_json.txt)

**Comment by lcb2099** [comment]
the configure of the portchannel is not complety。you can try this:
"PORTCHANNEL": {
        "PortChannel999": {
            "fallback": "true", 
            "min_links": "1", 
            "admin_status": "up", 
            "members": [
                "Ethernet48", 
                "Ethernet52"
            ], 
            "mtu": "9100"
        }
    },
