### ISSUE TITLE
many issues with 100bf-32x

### ISSUE THREAD

**Issue by msherman64** [Azure/SONiC#497]
I'm running the image from jenkins build 449  on the 100bf-32x
Most commands dealing with the hardware don't seem to work?

For example:
show interfaces status returns nothing
show interfaces tranceiver presence eprints a stack trace from sfpshow
show interfaces psustatus shows that none are present

Is it assumed that these should work "out of the box", or is there some configuration that I should do? What is the latest known working build for this platform?

Thanks for the help

**Comment by arkadiyshapiro** [comment]
Hi
Would you be able to file case directly with Barefoot support so we can help you out? support@barefootnetworks.com

**Comment by akokhan** [comment]
Hi @msherman64 ,
Could you please share the output of the following commands:
```
show version
docker ps -a
```
Thank you!

**Comment by msherman64** [comment]
Hi, Sorry for the delay. Upon returning to the project, I used ONIE to
install build 500, and it seems to have resolved the issues.

Thank you,
-Mike Sherman
