### ISSUE TITLE
ISIS packets do not come to FRRouting!!!??

### ISSUE THREAD

**Issue by ehsnsbn** [Azure/SONiC#502]
hello dear all,

besides BGP, i have enabled the other daemons inside the fpm-frr docker. the OSPF and LDP work fine, but the ISIS neighborship with CISCO does not come up. the SONIC router sends the IIH packets to cisco, the cisco sees them but the cisco's IIH packets do not reach FRRouting on SONIC.

would you please help me to solve it?
thanks and best regards,,

**Comment by ehsnsbn** [comment]
closed by no-reply! :(

**Comment by docker2017713** [comment]
hi ehsnsbn
   i want to know how enable ospfd and isisd in sonic , if config ospf ,the prompt “ospfd is not running ”in frr cli for sonic 。

**Comment by ydl-super** [comment]
@docker2017713 Hi ! Have you solved your problem?
