### ISSUE TITLE
libsaibcm misses libsai.so.1 symlink

### ISSUE THREAD

**Issue by lool** [Azure/SONiC#52]
Hi,

When unpacking SONiC libsaibcm debs, I'm missing libsai.so.1. Indeed, the actual lib – libsai.so.1.0 – is shipped in libsaibcm and libsaibcm-dev includes libsai.so, but I couldn't find libsai.so.1 (might be a mistake on my side?).

Cheers,
-- Loïc Minier

**Comment by stcheng** [comment]
lrwxrwxrwx root/root         0 2017-02-04 00:35 ./usr/lib/libsai.so.1 -> libsai.so.1.0

Fixed. The libsaibcm_*.deb package will be updated on the next version update.

**Comment by lool** [comment]
Awesome, thanks!
