### ISSUE TITLE
management interface cannot ping the other ip addresses!?

### ISSUE THREAD

**Issue by ehsnsbn** [Azure/SONiC#529]
hello,
the management interface can just ping its own ip address!, how can i solve it? thanks!

**root@R1:~# ethtool -i eth0**
driver: igb
version: 5.4.0-k
firmware-version: 0.0.0
expansion-rom-version: 
bus-info: 0000:00:14.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: no

**root@R1:~# cat /usr/share/sonic/templates/interfaces.j2**
auto lo
iface lo inet loopback
iface lo inet static
    address 1.1.1.1
    netmask 255.255.255.255

auto eth0
iface eth0 inet static
    address 192.168.1.10
    netmask 255.255.255.0
    network 192.168.1.0
    broadcast 192.168.1.255
    gateway 192.168.1.254

**kernel log**
Nov 30 17:01:16.835329 R1 INFO kernel: [ 1819.358782] igb 0000:00:14.0 eth0: igb: eth0 NIC Link is Up 100 Mbps Full Duplex, Flow Control: RX/TX
Nov 30 17:01:18.544612 R1 INFO ntpd[8526]: Listen normally on 6 eth0 192.168.1.10:123
Nov 30 17:01:18.545343 R1 INFO ntpd[8526]: Listen normally on 7 eth0 [fe80::72b3:d5ff:fecc:f15f%2]:123

**Comment by ToxicStoxm** [comment]
How did you resolve this issue?
