### ISSUE TITLE
Addition to Our Partners graphic?

### ISSUE THREAD

**Issue by jasonvds** [Azure/SONiC#577]
Today SoftIron has announced our HyperSwitch product line using SONiC. Is it possible to have our logo added to the partner graphic on the main SONiC page - https://azure.github.io/SONiC/?

http://cdn-media.softiron.com/images/1cc76076-180d-4b48-9e25-862973f600e7.png

**Comment by xinliu-seattle** [comment]
Welcome to the community SoftIron!, yes, we can add it to the WiKi. please give us a few days. thanks.

**Comment by jasonvds** [comment]
Thank you for adding this.
