### ISSUE TITLE
portstat fails

### ISSUE THREAD

**Issue by marian-pritsak** [Azure/SONiC#60]
Command output:
```
$ sudo portstat
[Errno 2] No such file or directory 2
```

**Comment by sihuihan88** [comment]
We are changing to read the port stat directly from database. After it is done, it will resolve this issue as well.

**Comment by jleveque** [comment]
Will be fixed by https://github.com/Azure/sonic-utilities/pull/19

**Comment by lguohan** [comment]
FIXED.
