### ISSUE TITLE
[NAT][documentation] Default SNAT DNAT miss packet rate value clarification needed

### ISSUE THREAD

**Issue by gcupryn** [Azure/SONiC#611]
In NAT design specification it is stated that:

// https://github.com/Azure/SONiC/blob/master/doc/nat/nat_design_spec.md

The SNAT or DNAT miss packets are by default rate limited to CPU @ 600pps.

On Wedge platform [using SONiC - HEAD.18-dirty-20200413.073958]:
```
Platform: x86_64-accton_wedge100bf_32x-r0
HwSKU: montara
ASIC: barefoot
Serial Number: AJ4900xxxx
```
in copp config file, default value is set to 6000:
docker exec -ti swss cat /etc/swss/config.d/00-copp.config.json
```
    {
        "COPP_TABLE:trap.group.nat.ip2me": {
            "trap_ids": "ip2me,src_nat_miss,dest_nat_miss",
            "trap_action":"trap",
            "trap_priority":"1",
            "queue": "1",
            "meter_type":"packets",
            "mode":"sr_tcm",
            "cir":"6000",
            "cbs":"6000",
            "red_action":"drop"
        },
        "OP": "SET"
    }
```

What value should be used as default on this platform/SONiC ?

**Comment by AkhileshSamineni** [comment]
@gcupryn  We have updated the CoPP rule with 600pps as part of PR https://github.com/Azure/sonic-swss/pull/1274 (https://github.com/Azure/sonic-swss/pull/1274/files#diff-7f752aaf658614192131c1075eae3f77)

**Comment by gcupryn** [comment]
Thanks @AkhileshSamineni !
All clear now.
