### ISSUE TITLE
rsyslog service failed to clean PID file before the docker quits

### ISSUE THREAD

**Issue by stcheng** [Azure/SONiC#62]
```[....] Starting enhanced syslogd: rsyslogdrsyslogd: pidfile '/var/run/rsyslogd.pid' and pid 29 already exist.```
This will prevent the docker from starting instantly.

**Comment by stcheng** [comment]
#453 is a temporary solution. Need to find a good way to handle scenarios when rsyslog service not gracefully shutdown

**Comment by lguohan** [comment]
resolved.
