### ISSUE TITLE
mellanox 2700 platform sensors spectrum max temp issue.

### ISSUE THREAD

**Issue by lguohan** [Azure/SONiC#68]
sensors shows that there're so the test failed
"Alarm on spectrum-i2c-2-48/temp1/temp1_input"

"temp1": {
                    "temp1_crit": "84.000", 
                    "temp1_input": "43.200",  <---- input equal to max. Looks like mellanox sensors issue
                    "temp1_max": "43.200", 
                    "temp1_min": "0.000"
                }

based on our understanding, temp1_max should be the threshold value, not the watermark.

**Comment by liatgrozovik** [comment]
fixed by https://github.com/Azure/sonic-buildimage/pull/541
