### ISSUE TITLE
How to turn on Auto-Negotiation

### ISSUE THREAD

**Issue by stormwindy** [Azure/SONiC#704]
Hi!

I have a Celestica Seastone DX010. I have "oper status" of all ports down. I assume the reason is that auto-negotiation on all ports are down. I couldn't find a command to turn on auto negotiation on the documents. How do I do that for all/select ports?

Thank you!

**Comment by mchomnic** [comment]
Hi,
The easiest way is to use json file.

echo '
{
  "PORT": {
    "Ethernet52": {
      "admin_status": "up",
      "autoneg": "1",
    }
  }
}' > auto_neg.json

sudo config load auto_neg.json -y

You can check interfaces status with:
1) "show interfaces status"
2) "portconfig -p Ethernet52 -l"
