### ISSUE TITLE
subinterface (subport) Error | switch crashing ! 

### ISSUE THREAD

**Issue by mipxman** [Azure/SONiC#714]
Hello
I have two devices **accton as-7712-32x** and **Ingrasys-s9100-32x** I installed last version of SONiC master on both of them. 

1. I haven't `config subinterface ...` subcommands ! so I try to config it via database configuration from [here](https://github.com/Azure/SONiC/blob/master/doc/subport/sonic-sub-port-intf-hld.md)
with `show subinterfaces status ` I can see the sub ports are created but after some minutes my swss docker container was Exited ! and switch NOT work correctly! 
![Screenshot from 2020-11-29 10-47-28](https://user-images.githubusercontent.com/66869651/100537081-9e48df80-323a-11eb-8ba1-54a4d80792d1.png)
![Screenshot from 2020-11-29 10-47-00](https://user-images.githubusercontent.com/66869651/100537082-a012a300-323a-11eb-88e7-49f5a80abe47.png)
![Screenshot from 2020-11-29 10-30-55](https://user-images.githubusercontent.com/66869651/100537084-a274fd00-323a-11eb-9ce3-158fdf8a8798.png)
![SAI](https://user-images.githubusercontent.com/66869651/100537088-a6088400-323a-11eb-94ef-44a87ca2e019.png)
![APP_DB](https://user-images.githubusercontent.com/66869651/100537089-a7d24780-323a-11eb-859b-cbc2c11fdfe9.png)

2. I try to use` ip link add link EthernetX name EthernetX.Y type vlan id Y ` linux command of iproute2 but after configuration the subport can't send/reply ICMP Echo. 
![arpsendicmpno](https://user-images.githubusercontent.com/66869651/100537153-48c10280-323b-11eb-83dc-0182a60a46f4.png)

![subinterface](https://user-images.githubusercontent.com/66869651/100537076-95580e00-323a-11eb-8714-dcf6ce626675.png)
![sub_2](https://user-images.githubusercontent.com/66869651/100537077-9721d180-323a-11eb-946e-1e7abee6d88c.png)
![STATE_DB](https://user-images.githubusercontent.com/66869651/100537079-9ab55880-323a-11eb-84aa-41c07f8f9d67.png)

**Comment by mipxman** [comment]
@wendani @lguohan can you help me ?

**Comment by mipxman** [comment]
here is my `show techsuport ` of accton-as7712-23x
[sonic_dump_sonic_20201129_081601.tar.gz](https://github.com/Azure/SONiC/files/5611894/sonic_dump_sonic_20201129_081601.tar.gz)

**Comment by wendani** [comment]
Your syslog shows process exits  due to the following
```
ov 29 07:25:18.882050 sonic ERR syncd#syncd: [0] SAI_API_SWITCH:brcm_sai_get_switch_attribute:3947 Error retreiving system mac.
Nov 29 07:25:18.882050 sonic ERR syncd#syncd: :- saiGetMacAddress: failed to get mac address: SAI_STATUS_ITEM_NOT_FOUND
Nov 29 07:25:18.882050 sonic NOTICE syncd#syncd: :- SaiSwitch: constructor took 2.113590 sec
Nov 29 07:25:18.883292 sonic NOTICE syncd#syncd: :- hardReinit: hard reinit took 6.193822 sec
Nov 29 07:25:18.887299 sonic NOTICE syncd#syncd: :- onSyncdStart: on syncd start took 6.320957 sec
Nov 29 07:25:18.887388 sonic ERR syncd#syncd: :- run: Runtime error during syncd init: :- saiGetMacAddress: failed to get mac address: SAI_STATUS_ITEM_NOT_FOUND
Nov 29 07:25:18.887447 sonic NOTICE syncd#syncd: :- sendShutdownRequest: sending switch_shutdown_request notification to OA for switch: oid:0x0
```

**Comment by mipxman** [comment]
> Your syslog shows process exits due to the following
> 
> ```
> ov 29 07:25:18.882050 sonic ERR syncd#syncd: [0] SAI_API_SWITCH:brcm_sai_get_switch_attribute:3947 Error retreiving system mac.
> Nov 29 07:25:18.882050 sonic ERR syncd#syncd: :- saiGetMacAddress: failed to get mac address: SAI_STATUS_ITEM_NOT_FOUND
> Nov 29 07:25:18.882050 sonic NOTICE syncd#syncd: :- SaiSwitch: constructor took 2.113590 sec
> Nov 29 07:25:18.883292 sonic NOTICE syncd#syncd: :- hardReinit: hard reinit took 6.193822 sec
> Nov 29 07:25:18.887299 sonic NOTICE syncd#syncd: :- onSyncdStart: on syncd start took 6.320957 sec
> Nov 29 07:25:18.887388 sonic ERR syncd#syncd: :- run: Runtime error during syncd init: :- saiGetMacAddress: failed to get mac address: SAI_STATUS_ITEM_NOT_FOUND
> Nov 29 07:25:18.887447 sonic NOTICE syncd#syncd: :- sendShutdownRequest: sending switch_shutdown_request notification to OA for switch: oid:0x0
> ```

How I must do ? set a static mac to sub port ?

**Comment by mipxman** [comment]
https://github.com/Azure/sonic-buildimage/issues/6167
