### ISSUE TITLE
How can we add a device on SONiC's supported list?

### ISSUE THREAD

**Issue by chienbernie** [Azure/SONiC#72]
If we want to add a device on SONiC's supported list, what should we do?
Thanks.

**Comment by stcheng** [comment]
Follow the [porting guide](https://github.com/Azure/SONiC/wiki/Porting-Guide) and make sure the current SONiC version works on the deivce and contact @lixinxu to add your device to the supported list.

**Comment by chienbernie** [comment]
What tests should we pass to prove that porting is working before contacting Xin Liu?
Is testing guide enough?

**Comment by xinliu-seattle** [comment]
Yes.

**Comment by lguohan** [comment]
@jleveque, to look at this.

**Comment by jleveque** [comment]
@chienbernie: You should ensure that your device passes the tests listed in the [testing guide](https://github.com/Azure/sonic-mgmt/blob/master/ansible/README.test.md), and also confirm that your platform-specific functionality works as expected. In the [platform porting guide](https://github.com/Azure/SONiC/wiki/Porting-Guide), each device-specific file's description contains a "Testing" section which describes how to test the functionality of that file.

Please reply here with further questions or if you feel anything in the porting guide is unclear.

**Comment by jleveque** [comment]
@chienbernie: As it's been a few months since this issue has been updated, I assume you have no further questions so I am closing this issue. If you have questions in the future, please open a new issue. Thanks.
