### ISSUE TITLE
Does SONiC support Dell S6010-ON?

### ISSUE THREAD

**Issue by haslersn** [Azure/SONiC#730]
The Dell S6010-ON is currently not on SONiC's list of supported devices. Does this mean that the switch will not work with SONiC, or is there a chance that it works nonetheless? Did anybody try out SONiC on that switch?

**Comment by paulmenzel** [comment]
I think, you have to find out for yourself. From a quick look, it could be that the Dell S6000, added in merge/pull request https://github.com/Azure/SONiC-buildimage/pull/624, might be the same hardware. (The specification sheets are from different years, and do not list the switching ASIC.)

1. [Dell S6000 specification sheet](https://i.dell.com/sites/csdocuments/Shared-Content_data-Sheets_Documents/en/Dell_Networking_S6000_Spec_Sheet.pdf)
2. [Dell S6010-ON specification sheet](https://i.dell.com/sites/doccontent/shared-content/data-sheets/en/Documents/Dell-Networking-S-Series-S6010-ON-Spec-Sheet.pdf)

If a separate port is needed, I would first contact Dell and ask them to make the port. If they refuse, you could try to do it yourself or contract a company.

Anyway, I believe the mailing list is a better place for these types of questions, and I recommend to close this issue.

**Comment by shodanx2** [comment]
Hi,

I'm curious, did you try it ? 
I also have an S6010-ON and I'd like to try SONiC !

Note
S6000-ON is a Broadcom StrataXGS Trident II BCM56850 (on the supported devices list)
S6010-ON is a Broadcom StrataXGS Trident II+ BCM56860  (not on the supported devices list)
S6100-ON is a Broadcom Tomahawk BCM?????? (on the supported devices list)

According to this page

https://sonic-net.github.io/SONiC/Supported-Devices-and-Platforms.html

all broadcom are supported by the same bin (this link is broken)

[sonic-broadcom.bin](https://artprodcus3.artifacts.visualstudio.com/Af91412a5-a906-4990-9d7c-f697b81fc04d/be1b070f-be15-4154-aade-b1d3bfb17054/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL21zc29uaWMvcHJvamVjdElkL2JlMWIwNzBmLWJlMTUtNDE1NC1hYWRlLWIxZDNiZmIxNzA1NC9idWlsZElkLzUxMjU1L2FydGlmYWN0TmFtZS9zb25pYy1idWlsZGltYWdlLmJyb2FkY29t0/content?format=file&subpath=/target/sonic-broadcom.bin)


That is quite a lot of models !

Broadcom 	Helix 5
Broadcom 	Helix4
Broadcom 	Tomahawk
Broadcom 	Tomahawk 2
Broadcom 	Tomahawk 3
Broadcom 	Tomahawk 4
Broadcom 	Tomahawk 5
Broadcom 	Trident 2
Broadcom 	Trident 3
Broadcom 	Trident 3.X2
Broadcom 	Trident 3.X3
Broadcom 	Trident 3.X5
Broadcom 	Trident 4.X11
Broadcom 	Trident 4.X9

But not Trident 2+, at least not explicitely 
 
The BCM56850 is Trident II
The BCM56860 is Trident II+

https://people.ucsc.edu/~warner/Bufs/trident2
https://people.ucsc.edu/~warner/Bufs/StrataXGS_Trident_II_presentation.pdf
https://people.ucsc.edu/~warner/Bufs/trident-II+.pdf
https://people.ucsc.edu/~warner/Bufs/Broadcom-OCP-Trident2-leaf-spine.pdf
https://www.broadcom.com/products/ethernet-connectivity/switching/strataxgs/bcm56850-series
https://www.broadcom.com/products/ethernet-connectivity/switching/strataxgs/bcm56860-series
