### ISSUE TITLE
How to config the SONiC

### ISSUE THREAD

**Issue by 123toorc** [Azure/SONiC#735]
Hi, the MIGHTY team of SONiC Azure

I'm new to SONiC, I need some help. I have a switch that running with SONiC. There is a machine connect with it through 100GbE, and they also connect with a 1GbE router. (DHCP server for my switch manage interface eth0)

 How should I config it to let another machine can connect it through the 100GbE port? Except for the management interface, eth0, which other interfaces should be the host for the another range network?  Is there any instruction from scratch?

 I also don't understand why SONiC OS has so many interfaces, from Ethernet0 to Ethernet 124. What are these, please tell me some idea or the link, I'm sorry, I'm not good at this, please help me!

**Comment by TETA-Net** [comment]
> How should I config it to let another machine can connect it through the 100GbE port?

you can add ip address to your 100G interface p2p . 

For example : 
```
admin@sonic:~$ sudo config interface ip add Ethernet0 192.168.100.100/24 
```
if the the nexthop in the network `192.168.100.0/24` you can ssh ti switch via `192.168.100.100`

`What are these, please tell me some idea or the link`
it is dependent on your hardware and asic. can you tell me what is your device ?

**Comment by 123toorc** [comment]
@TETA-Net  thanks for the comment, I already fixed the problem..
