### ISSUE TITLE
Switch blocked the package from server side

### ISSUE THREAD

**Issue by 123toorc** [Azure/SONiC#737]
Set up:
   Server1 <-> Switch <-> Server2

Configuration:
   The server connects to Switch via a dual-port.
   I have set up a Vlan1000, which has four physic interface Ethernet0 Ethernet4 (server1) and Ethernet64 Ethernet68 (server2)
   The Vlan1000 interface IP set is 192.168.3.1,  and server1 has 192.168.3.2 and 192.168.3.3; server2 has 192.168.3.4 and 192.168.3.5

Problem: 
 
   After I ping from the switch to the server, I tcpdump the server's network interface, the output is weird, it receives the arp request from the switch ping, however, its reply never get to the switch. It looks like the switch blocks the package send from the server. If I ping from the server to the switch, and I tcpdump the Vlan interface, the arp request never gets there. 

   The Vlan is the trunk, in my understanding, it should be access status in my opinion since there is no other switch in my set up so far. under the same Vlan, the connection should be direct and clear. 

Please tell me how to fix it? If there is any info you need please let me know. 

Thanks, 
Tong

**Comment by TETA-Net** [comment]
in the switch 1 

 1.please get show ip address by `show ip interfaces`
 2. remove ip address from your interfaces by ` sudo config interface remove Ethernet0 A.B.C.D/M`
 3. create vlan ` sudo config vlan add 1000`
 4. add member to Vlan untagged ` sudo config vlan member add 100 Ethernet0 -u ` 
do it for all interfaces. Now it's not need to set ip in your interface Vlan1000.

**Comment by 123toorc** [comment]
@TETA-Net  thanks for the comment, I already fixed the problem..
