### ISSUE TITLE
Is there a build-in test tool for SAI APIs?

### ISSUE THREAD

**Issue by chienbernie** [Azure/SONiC#74]
Is there a build-in test tool for SAI APIs?
Or how can I test SAI APIs in SONiC?
Thanks.

**Comment by stcheng** [comment]
https://github.com/opencomputeproject/SAI/tree/master/test this could be a reference.

**Comment by jleveque** [comment]
@chienbernie: As it's been a few months since this issue has been updated, I assume you have no further questions so I am closing this issue. If you have questions in the future, please open a new issue. Thanks.
