### ISSUE TITLE
Support for 802.1x port-based authentication

### ISSUE THREAD

**Issue by jcrist-nexcess** [Azure/SONiC#744]
I noticed that there is a [SONiC wpa_supplicant repo](https://github.com/Azure/sonic-wpa-supplicant), and SONiC.202106 Roadmap lists improvements to Radius AAA. Does the SONiC WPA_Supplicant Plugin support or plan on supporting 802.1x authentication method in the interface configuration?

**Comment by caizhenghui-juniper** [comment]
The inclusion of wpa_supplicant is for MACSec at the moment.

**Comment by storrgie** [comment]
Wondering if if I could bump for a re-open and clarification on this one. Is it a roadmap item to support port-pased authentiation via, likely hostapd as a supplicant?
