### ISSUE TITLE
Question regarding SONIC_ONLINE_DEBS 

### ISSUE THREAD

**Issue by Balaselvi** [Azure/SONiC#75]
Hello,
I am Balaselvi.
We are planning to do a pull request to add our device(Inventec) support with SONiC shortly.

I have a query regarding the creation of libsai.deb file which is dowloaded and installed in SONiC.
If we have to add our configuration file inside the etc/bcm (for ex: th-d7032-32x100g.config.bcm) folder which is installed using the libsaibcm_2.1.5.1-20170303234832.14_amd64.deb package by the SONiC, whom should we contact, either Broadcom or SONiC?

This package which is downloaded from "https://sonicstorage.blob.core.windows.net/packages/" is maintained by SONiC and this addition of configuration files will be covered in the pull request with SONiC is my understanding.

Please clarify the procedure.

Thank you.

Thanks and regards,
Bala

**Comment by stcheng** [comment]
I am currently maintaining the Broadcom debs used by SONiC. Please contact me <shuche@microsoft.com> so that I could help adding the config.bcm file into the libsaibcm deb package. For the rest porting information, please follow https://github.com/Azure/SONiC/wiki/Porting-Guide.

**Comment by Balaselvi** [comment]
Hi Stcheng,

Thanks for the prompt response.

Thanks and regards,
Bala
