### ISSUE TITLE
How I push CLI commands to a switch using REST?

### ISSUE THREAD

**Issue by asydney** [Azure/SONiC#775]
Hi SONiC folks,
                         I was able to configure a virtual testbed of SONiC switches and below is just a snippet of some of the following commands:
"""
sonic> sudo config interface ip remove Ethernet16 10.0.0.8/31
sonic> sudo config interface ip add Ethernet16 10.10.1.2/31
sonic> sudo config interface ip add Loopback0 10.0.1.13/32
sonic> sudo vtysh
sonic> configure t
sonic> no router bgp 65100
sonic> router bgp 65021
sonic> bgp router-id 10.0.1.13
"""

Questions:
Can I push these configurations remotely via REST?
* If yes, can you kindly point to documentation on how? In particular, do I need to install rest specific containers as shown here https://github.com/Azure/sonic-restapi? In fact, I have installed this on a switch as a test, but it's still unclear how to push CLI commands.
* At the moment, I do see a "/usr/sbin/rest_server" process running and perhaps attached to port 443? So maybe all I do need is a REST client on the host to push the configs? If yes, can you point me to documentation setting up the client (Perhaps a "curl" example?)?

Thanks,
-Syd

**Comment by gcupryn** [comment]
Hi @asydney , please check 
https://github.com/Azure/SONiC/blob/master/doc/mgmt/Management%20Framework.md 
Paragraph 3.2.2.4.15 API documentation 

Ideally you should be able to access https://<YOUR_IP>/ui 
from there you can find various example, , leaving one for reference :

curl -X GET "https://<my_box_IP>/restconf/data/sonic-port:sonic-port" -H "accept: application/yang-data+json"

**Comment by asydney** [comment]
Great thanks!

**Comment by asydney** [comment]
Update:
I've been able to run the CURL command mentioned in the previous reply, in addition to other interface/port commands shown from the web portal (i.e. https://<YOUR_IP>/ui). 

However, I can't seem to find REST options for CLI calls such as `show version`. So to be a bit specific, can someone kindly point me to the REST option from https://<YOUR_IP>/ui or perhaps the CURL commands to do the following?


```
sonic> sudo config interface ip remove Ethernet16 10.0.0.8/31
sonic> sudo config interface ip add Ethernet16 10.10.1.2/31
sonic> sudo config interface ip add Loopback0 10.0.1.13/32
sonic> sudo vtysh
sonic> configure t
sonic> no router bgp 65100
sonic> router bgp 65021
sonic> bgp router-id 10.0.1.13
```

**Comment by gcupryn** [comment]
Hi @asydney , 
I have no idea if we can run cli command over REST.

is there any reason why those commands have to go via REST ? 
Why not using SSH ?

**Comment by asydney** [comment]
Based on the [sonic management framework documentation](https://github.com/Azure/SONiC/blob/master/doc/mgmt/Management%20Framework.md#sonic-management-framework), it appears that one can leverage HTTP methods such as GET and POST to achieve the same results as executing the commands via the CLI. As mentioned before, when I access the REST server's web interface (i.e. via https://REST_SERVER_IP/ui), I am able to see various HTTP methods for certain switch configurations(e.g. options to configure interfaces etc.). However, I can't find any HTTP options to do things like a) view the switch version, b) configure BGP (and in my previous reply, I have provided sample BGP CLI commands that I can't seem to find the HTTP equivalent).

With regards to "... any reason why those commands have to go via REST?", we've got an environment where we would like to control all devices externally at will.

PS. Also, the documentation does mention that all CLI commands are translated to REST calls under the hood for the REST server. So I would image that perhaps external control by a REST client is supported?

**Comment by gcupryn** [comment]
I think there maybe some misunderstanding with statement that any CLI command is translated to REST call.

The justification of the above is because of fact how i.e. CLI command 'show version' is implemented in SONiC, please take a look on the implementation.
Calling 
`admin@sonic:~$ show version`

actually calls python script : 
`/usr/local/lib/python3.7/dist-packages/show/main.py`

`
#
# 'version' command ("show version")
#

@cli.command()
@click.option("--verbose", is_flag=True, help="Enable verbose output")
def version(verbose):
    """Show version information"""
    version_info = device_info.get_sonic_version_info()

    platform = device_info.get_platform()
    hwsku = device_info.get_hwsku()
    asic_type = version_info['asic_type']
    asic_count = multi_asic.get_num_asics()

    serial_number_cmd = "sudo decode-syseeprom -s"
    serial_number = subprocess.Popen(serial_number_cmd, shell=True, text=True, stdout=subprocess.PIPE)

    sys_uptime_cmd = "uptime"
    sys_uptime = subprocess.Popen(sys_uptime_cmd, shell=True, text=True, stdout=subprocess.PIPE)

    click.echo("\nSONiC Software Version: SONiC.{}".format(version_info['build_version']))
    click.echo("Distribution: Debian {}".format(version_info['debian_version']))
    click.echo("Kernel: {}".format(version_info['kernel_version']))
    click.echo("Build commit: {}".format(version_info['commit_id']))
    click.echo("Build date: {}".format(version_info['build_date']))
    click.echo("Built by: {}".format(version_info['built_by']))
    click.echo("\nPlatform: {}".format(platform))
    click.echo("HwSKU: {}".format(hwsku))
    click.echo("ASIC: {}".format(asic_type))
    click.echo("ASIC Count: {}".format(asic_count))
    click.echo("Serial Number: {}".format(serial_number.stdout.read().strip()))
    click.echo("Uptime: {}".format(sys_uptime.stdout.read().strip()))
    click.echo("\nDocker images:")
    cmd = 'sudo docker images --format "table {{.Repository}}\\t{{.Tag}}\\t{{.ID}}\\t{{.Size}}"'
    p = subprocess.Popen(cmd, shell=True, text=True, stdout=subprocess.PIPE)
    click.echo(p.stdout.read())
`
Please note that in above implementation  there is no translation to REST calls, what is more there are local calls to 
subprocess.Popen which by nature are local to caller context.

Of course above implementation doesn't prevent case when reset server would understand request to execute locally 'show version' and return output via REST - but I didn't find a way to do it.

**Comment by asydney** [comment]
Ah got it.
Do you know if this is also the case for BGP style commands(i.e. that these are not translated into REST calls but use python subprocesses)? For example:

```
sonic> no router bgp 65100
sonic> router bgp 65021
sonic> bgp router-id 10.0.1.13
```

**Comment by gcupryn** [comment]
BGP style command AFAIK are called from vtysh  tool.
In fact this is yet another tool/utility which runs locally,

`admin@sonic:~$ which vtysh
/usr/bin/vtysh

admin@sonic:~$ file /usr/bin/vtysh
/usr/bin/vtysh: Bourne-Again shell script, ASCII text executable
`

/usr/bin/vtysh shell scripts invokes 'docker exec -ti bgp  vtysh'

I have found vtysh documentation here : https://docs.frrouting.org/en/latest/vtysh.html ,
but I'm not sure if this will help you in any way.

**Comment by asydney** [comment]
Thanks. I'll close this one out.
