### ISSUE TITLE
How can I copy whole SONiC project to local git server?

### ISSUE THREAD

**Issue by chienbernie** [Azure/SONiC#78]
I want to copy whole SONiC project including submodules to our local git server for developing.
How can I do this?
Thanks.

**Comment by lguohan** [comment]
https://github.com/Azure/sonic-buildimage/blob/master/README.md

2017-05-09 21:11 GMT-07:00 Bernie Chien <notifications@github.com>:

**Comment by chienbernie** [comment]
This README.md is showing how to clone SONiC source and build it.
I can do this. I want to create a same project at my local git server.
I want to know how many submodules in this project and is there a easy way to clone github project.
Thanks.

**Comment by lguohan** [comment]
i am not sure the question since you can clone everything from build-image.

**Comment by chienbernie** [comment]
I tried to move this project to gitlab which is not supporting git submodule directly.
I have found a way to clone sonic from github. 
Thanks.
