### ISSUE TITLE
make configure PLATFORM=barefoot is throwing error.

### ISSUE THREAD

**Issue by shivkumar301** [Azure/SONiC#812]
We are building SONiC with Intel Barefoot SDE 9.5.0. While executing the below command we are getting errors as shown in the attached image.
We are using Ubuntu 20.04.2 LTS.

**Command :** `make configure PLATFORM=barefoot`

We couldn't solve the errors with the solutions mentioned in the search results we got from google.
Could anyone help us solve this error?

**Error:**
![error_24by61](https://user-images.githubusercontent.com/13508717/124350966-509fb580-dc15-11eb-8e05-519a65a20afb.png)

**Comment by gcupryn** [comment]
Hi,
out of curiosity , is the error also seen for other PLATFORMs ?

If possible can you attach whole log from the very beginning ?

**Comment by mchomnic** [comment]
Shiv, did you use docker image to build SONiC over Ubuntu?

**Comment by shivkumar301** [comment]
> Shiv, did you use docker image to build SONiC over Ubuntu?

You got it @mchomnic 😄. We were installing it without using docker. When we tried building this image with docker and it worked.
