### ISSUE TITLE
Frequently write DB will cause the memory usage increase permanently. Seems like there is a memory leak problem.

### ISSUE THREAD

**Issue by roooockwell** [Azure/SONiC#82]
Hi,
    When I manually do some  actions which will write redisDB frequently:
    1.change the state of 8000 arp entry over and over again.
   ` ip neighbour replace xx.xx.xx.xx nud xxxx dev Ethernetxxx`
    2.add and delete 1000 static routes over and over agein.
  `  ip route add/del xx.xx.xx.xx/xx via xx.xx.xx.xx`
    The memory usage of redis-server will increase.
    After I stop the actions, the memory usage of redis-server will not drop to the normal state.
    Seems like there is a memory leak problem about redis-server or something related to redis-server.
![top 1](https://cloud.githubusercontent.com/assets/28422151/26050812/b19f7098-3992-11e7-8c76-c6a0ea4cc897.png)

**Comment by stcheng** [comment]
could you do a `show version` to track which version has such issue?

**Comment by roooockwell** [comment]
Sorry there are some problems about my image.
I will tell if i still have this problem after I reproduce this problem.

**Comment by stcheng** [comment]
thanks

**Comment by pavel-shirshov** [comment]
Hi roooockwell,

Please check your py-swsssdk is new enough.
I fixed a memory leak in the following commit
https://github.com/Azure/sonic-py-swsssdk/commit/4cf7a59a5ffa74784f8067484b0dbee51433c184

**Comment by jleveque** [comment]
I assume roooockwell's thumbs-up reaction implies this issue was resolved, so I am closing this.
