### ISSUE TITLE
EVPN_NVO Vxlan would not be deleted when delete all Vxlan

### ISSUE THREAD

**Issue by Ariadw** [Azure/SONiC#828]
**We do not triage issue for this repo. All issues are triaged in Azure/sonic-buildimage repo**
when I test the sonic-vxlan.yang,I can not delete the data what I was posted in redis configDB .
deleting VXLAN_TUNNEL failed

error log:Delete will violate the constraint as entry VXLAN_TUNNEL is referred in EVPN_NVO|str

EVPN_NVO in sonic-vxlan.yang
container EVPN_NVO {

            list EVPN_NVO_LIST { 

                key "name";
                max-elements 1;

                leaf name {
                    type string;
                }

                leaf source_vtep {
                    mandatory true;
                    type leafref {
                        path "../../../VXLAN_TUNNEL/VXLAN_TUNNEL_LIST/name";
                    }
                }
            }
        }

**Comment by bluecmd** [comment]
Hi @Ariadw  - this repository is only for the SONiC website, you probably want to file your issue over at https://github.com/Azure/sonic-buildimage!
