### ISSUE TITLE
Is the source code of Marvell published?

### ISSUE THREAD

**Issue by chienbernie** [Azure/SONiC#83]
I saw that RD-BC3-4825G6CG-A4 	Marvell 	Prestera 98CX84xx 	6x100G+48x25G is on supporting list.
Where can I find the source code of this device for reference?
Thanks.

**Comment by VitalyVovnoboy** [comment]
https://github.com/Azure/sonic-buildimage/tree/master/platform/marvell
https://github.com/Marvell-switching/SAI-plugin

**Comment by chienbernie** [comment]
Got it. Thanks.
