### ISSUE TITLE
Dynamic Port Breakout on Wedge100bf-65x, it can't be enabled, console show "Failed to break out Port"

### ISSUE THREAD

**Issue by robert1030** [Azure/SONiC#834]
**SONiC version**
SONiC.master.179-dirty-20210419.034457

**What i do**
1. config interface breakout Ethernet0 4x25G[10G]
2. To check Port can be break out or not

**Expected result:**
   Port can be break out

**Observed result:**
   Port can't be break out

**Error message:**
config interface breakout Ethernet0 4x25G[10G]
Do you want to Breakout the port, continue? [y/N]: y

Running Breakout Mode : 1x100G[40G] 
Target Breakout Mode : 4x25G[10G]

Ports to be deleted : 
 {
    "Ethernet0": "100000"
}
Ports to be added : 
 {
    "Ethernet0": "25000",
    "Ethernet1": "25000",
    "Ethernet2": "25000",
    "Ethernet3": "25000"
}

After running Logic to limit the impact

Final list of ports to be deleted : 
 {
    "Ethernet0": "100000"
} 
Final list of ports to be added :  
 {
    "Ethernet0": "25000",
    "Ethernet1": "25000",
    "Ethernet2": "25000",
    "Ethernet3": "25000"
}
Loaded below Yang Models
['sonic-acl', 'sonic-breakout_cfg', 'sonic-crm', 'sonic-device_metadata', 'sonic-device_neighbor', 'sonic-extension', 'sonic-flex_counter', 'sonic-interface', 'sonic-loopback-interface', 'sonic-port', 'sonic-portchannel', 'sonic-types', 'sonic-versions', 'sonic-vlan', 'sonic-vrf']
Note: Below table(s) have no YANG models:
BGP_NEIGHBOR, FEATURE, KDUMP, SNMP, SNMP_COMMUNITY, 
sonic_yang(3):All Keys are not parsed in DEVICE_METADATA
dict_keys(['buffer_model'])
sonic_yang(3):exceptionList:[]
sonic_yang(3):Data Loading Failed:All Keys are not parsed in DEVICE_METADATA
dict_keys(['buffer_model'])
Data Loading Failed
All Keys are not parsed in DEVICE_METADATA
dict_keys(['buffer_model'])
ConfigMgmt Class creation failed
Failed to break out Port. Error: Failed to load the config. Error: ConfigMgmtDPB Class creation failed

**Comment by bluecmd** [comment]
Hi @robert1030 - this repository is only for the SONiC website, you probably want to file your issue over at https://github.com/Azure/sonic-buildimage!

**Comment by mchomnic** [comment]
Hi @robert1030,
Dynamic Port Breakout is not yet supported in Wedge platforms with Tofino ASIC. Please, use static port breakout with follow commands:

echo '
{
  "PORT": {
    "Ethernet0": {
      "admin_status": "up",
      "alias": "Ethernet0",
      "autoneg": "off",
      "description": "Ethernet0",
      "fec": "rs",
      "index": "0",
      "lanes": "0",
      "mtu": "9100",
      "speed": "25000"
    },
    "Ethernet1": {
      "admin_status": "up",
      "alias": "Ethernet1",
      "autoneg": "off",
      "description": "Ethernet1",
      "fec": "rs",
      "index": "0",
      "lanes": "1",
      "mtu": "9100",
      "speed": "25000"
    },
    "Ethernet2": {
      "admin_status": "up",
      "alias": "Ethernet2",
      "description": "Ethernet2",
      "autoneg": "off",
      "fec": "rs",
      "index": "0",
      "lanes": "2",
      "mtu": "9100",
      "speed": "25000"
    },
    "Ethernet3": {
      "admin_status": "up",
      "alias": "Ethernet3",
      "description": "Ethernet3",
      "autoneg": "off",
      "fec": "rs",
      "index": "0",
      "lanes": "3",
      "mtu": "9100",
      "speed": "25000"
    }
  }
}' > port_breakout.json
sudo config load port_breakout.json -y
sudo config save -y
sudo config reload -y

Of course, you can set fec and autoneg depend on your need.

**Comment by robert1030** [comment]
Hi guys:
static port breakout to work on Wedge100bf-65x, the issue will be closed
