### ISSUE TITLE
libsai segfault on the New Ported Broadcom Platform Target

### ISSUE THREAD

**Issue by pollyhsu2git** [Azure/SONiC#84]
1) SONic git base: Jenkins#199
2) New platform/broadcom target: AS7712-32x
3) saibcm and opennsl version in the syncd docker
```
root@sonic:/home/admin# docker exec -it syncd bash
root@sonic:/# dpkg -l | grep saibcm
ii  libsaibcm                  2.1.5.1-6+0~20170510001051.32~1.gbpfa5013 amd64        Switch Abstraction Interface sdk based on Broadcom opennsl
root@sonic:/#
root@sonic:/# dpkg -l | grep opennsl
ii  libopennsl                 3.2.2.2-7+0~20170512003351.39~1.gbp6fccd7 amd64        shared library for Broadcom opennsl sdk
ii  libsaibcm                  2.1.5.1-6+0~20170510001051.32~1.gbpfa5013 amd64        Switch Abstraction Interface sdk based on Broadcom opennsl
```
4) syncd core dumpe zip: sonic_dump_sonic_20010101_021135-syncd.tar.gz
[sonic_dump_sonic_20010101_021135-syncd.tar.gz](https://github.com/Azure/SONiC/files/1010050/sonic_dump_sonic_20010101_021135-syncd.tar.gz)

**Comment by pollyhsu2git** [comment]
The following is the GREPed segment of 'syncd` in syslog.

syncd reported that  `Common SDK init completed#015#015` so it seems to us that our config.bcm is free from the compatibility issue here.

####
 an  1 01:20:24.0 sonic ERR syncd: :- get_attr_name: object type 20 attr id 256 not found in map!
Jan  1 01:20:24.0 sonic NOTICE syncd: :- handleCmdLine: enable diag shell
Jan  1 01:20:24.0 sonic NOTICE syncd: :- handleCmdLine: profile map file: /usr/share/sonic/hwsku/sai.profile
Jan  1 01:20:24.0 sonic WARNING syncd: :- handleProfileMap: not found '=' in line
Jan  1 01:20:24.0 sonic NOTICE syncd: :- isVeryFirstRun: First Run: True
Jan  1 01:20:24.0 sonic NOTICE syncd: :- main: starting initializing ASIC
Jan  1 01:20:24.0 sonic NOTICE syncd: :- loadRedisScript: lua script loaded, sha: e70c5f65367f8b9fed2deb3daa5ee4ba40f90c58
Jan  1 01:20:24.0 sonic INFO supervisord: syncd [6] daemon mode
Jan  1 01:20:24.0 sonic INFO supervisord: syncd Platform configuration file "/etc/bcm/th-as7712-32x100G.config.bcm" is used
Jan  1 01:20:24.0 sonic INFO supervisord: syncd #015
Jan  1 01:20:24.0 sonic INFO supervisord: syncd Platform Boot flags: 0x0
Jan  1 01:20:24.0 sonic INFO supervisord: syncd #015
Jan  1 01:20:24.0 sonic INFO supervisord: syncd Defaulting the board ID to Broadcom reference platform.
Jan  1 01:20:24.0 sonic INFO supervisord: syncd #015
Jan  1 01:20:24.141216 sonic INFO lldp.sh[1739]: 2001-01-01 01:20:24,140 INFO spawned: 'lldp-syncd' with pid 29
Jan  1 01:20:24.0 sonic INFO lldp-syncd [lldp_syncd] INFO: Starting SONiC LLDP sync daemon...
Jan  1 01:20:25.0 sonic INFO supervisord: start.sh syncd: started
Jan  1 01:20:25.143486 sonic INFO lldp.sh[1739]: 2001-01-01 01:20:25,142 INFO success: lldp-syncd entered RUNNING state, process has
 stayed up for > than 1 seconds (startsecs)
Jan  1 01:20:25.0 sonic INFO supervisord: start.sh lldp-syncd: started
Jan  1 01:20:25.0 sonic INFO supervisord: syncd DMA pool size: 16777216#015
Jan  1 01:20:27.0 sonic INFO supervisord: syncd PCI unit 0: Dev 0xb960, Rev 0x11, Chip BCM56960_B0, Driver BCM56960_A0#015
Jan  1 01:20:27.0 sonic INFO supervisord: syncd #015#015
Jan  1 01:20:27.0 sonic INFO supervisord: syncd Initializing platform#015#015
Jan  1 01:20:27.0 sonic INFO supervisord: syncd SOC unit 0 attached to PCI device BCM56960_B0#015
Jan  1 01:20:27.0 sonic INFO supervisord: syncd Boot flags: Cold boot#015
Jan  1 01:20:27.0 sonic INFO supervisord: syncd rc: unit 0 device BCM56960_B0#015
Jan  1 01:20:27.0 sonic INFO supervisord: syncd *** unit 0: configured for normal latency#015
Jan  1 01:20:27.0 sonic INFO supervisord: fpmsyncd Connected!
Jan  1 01:20:27.0 sonic INFO supervisord: syncd rc: MMU initialized#015
Jan  1 01:20:28.0 sonic INFO supervisord: syncd *** unit 0: ports capable of limited speed range cut-thru#015
Jan  1 01:20:28.0 sonic INFO supervisord: syncd rc: L2 Table
Jan  1 01:20:28.0 sonic INFO supervisord: syncd shadowing enabled#015
Jan  1 01:20:28.0 sonic INFO supervisord: syncd rc: Port modes initialized
Jan  1 01:20:28.0 sonic INFO supervisord: syncd #015
Jan  1 01:20:28.0 sonic INFO supervisord: syncd Common SDK init completed#015#015
Jan  1 01:20:30.0 sonic INFO supervisord 2001-01-01 01:20:24,140 INFO spawned: 'lldp-syncd' with pid 29
Jan  1 01:20:30.0 sonic INFO supervisord 2001-01-01 01:20:25,142 INFO success: lldp-syncd entered RUNNING state, process has stayed
up for > than 1 seconds (startsecs)
Jan  1 01:20:30.908787 sonic INFO kernel: [  146.528521] syncd[2202]: segfault at 0 ip 00007f88b67248c3 sp 00007fff46ae61e0 error 6
in libsai.so.1.0[7f88b66ce000+94000]
Jan  1 01:20:31.0 sonic INFO supervisord 2001-01-01 01:20:22,734 INFO spawned: 'fpmsyncd' with pid 50
Jan  1 01:20:31.0 sonic INFO supervisord 2001-01-01 01:20:23,787 INFO success: fpmsyncd entered RUNNING state, process has stayed up
 for > than 1 seconds (startsecs)
Jan  1 01:20:32.0 sonic INFO supervisord: syncd [5] child exited status: 139
Jan  1 01:20:32.0 sonic INFO supervisord 2001-01-01 01:20:23,702 INFO spawned: 'syncd' with pid 17
Jan  1 01:20:32.0 sonic INFO supervisord 2001-01-01 01:20:25,074 INFO success: syncd entered RUNNING state, process has stayed up fo
r > than 1 seconds (startsecs)
#####

**Comment by pollyhsu2git** [comment]
The following was what we got from `gdb`
#####
root@sonic:/# gdb /usr/bin/syncd
GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/syncd...(no debugging symbols found)...done.
(gdb)  run --diag -p /usr/share/sonic/hwsku/sai.profile
Starting program: /usr/bin/syncd --diag -p /usr/share/sonic/hwsku/sai.profile
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff1764700 (LWP 83)]
Platform configuration file "/etc/bcm/th-as7712-32x100G.config.bcm" is used
Platform Boot flags: 0x0
Defaulting the board ID to Broadcom reference platform.
[New Thread 0x7ffff7fe8700 (LWP 84)]
DMA pool size: 16777216
PCI unit 0: Dev 0xb960, Rev 0x11, Chip BCM56960_B0, Driver BCM56960_A0

Initializing platform
[New Thread 0x7ffff7e26680 (LWP 85)]
[New Thread 0x7ffff7e20700 (LWP 86)]
SOC unit 0 attached to PCI device BCM56960_B0
Boot flags: Cold boot
rc: unit 0 device BCM56960_B0
*** unit 0: configured for normal latency
[New Thread 0x7ffff7e18700 (LWP 87)]
rc: MMU initialized
*** unit 0: ports capable of limited speed range cut-thru
[New Thread 0x7ffff7e14700 (LWP 88)]
[New Thread 0x7ffff7e0c700 (LWP 89)]
[New Thread 0x7ffff7e04700 (LWP 90)]
[New Thread 0x7ffff083e700 (LWP 91)]
[Thread 0x7ffff7e04700 (LWP 90) exited]
[Thread 0x7ffff083e700 (LWP 91) exited]
[New Thread 0x7ffff7e04700 (LWP 92)]
[Thread 0x7ffff7e04700 (LWP 92) exited]
[New Thread 0x7ffff083e700 (LWP 93)]
[Thread 0x7ffff083e700 (LWP 93) exited]
[New Thread 0x7ffff7e04700 (LWP 94)]
[Thread 0x7ffff7e04700 (LWP 94) exited]
[New Thread 0x7ffff7e04700 (LWP 95)]
[New Thread 0x7ffff083e700 (LWP 96)]
[New Thread 0x7ffff0836700 (LWP 97)]
[New Thread 0x7ffff082e700 (LWP 98)]
rc: L2 Table shadowing enabled
[New Thread 0x7ffff0826700 (LWP 99)]
rc: Port modes initialized
Common SDK init completed

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff77068c3 in _brcm_sai_indexed_data_set () from /usr/lib/libsai.so.1
(gdb)

**Comment by pollyhsu2git** [comment]
[sonic_dump_sonic_20010101_005626-n205-host.tar.gz](https://github.com/Azure/SONiC/files/1020808/sonic_dump_sonic_20010101_005626-n205-host.tar.gz)
@lguohan 
we've tried
5. SONic git base: Jenkins#205, got the same libsai segfault and we'll post a segment of `syncd`
[sonic_dump_sonic_20010101_005626-n205-host.tar.gz](https://github.com/Azure/SONiC/files/1020805/sonic_dump_sonic_20010101_005626-n205-host.tar.gz)
 log later
6. saibcm and opennsl version in the syncd docker
root@sonic:/# dpkg -l | grep saibcm
ii  libsaibcm                  2.1.5.1-7+0~20170519212441.39~1.gbpc7b67f amd64        Switch Abstraction Interface sdk based on Broa
dcom opennsl
root@sonic:/# dpkg -l | grep opennsl
ii  libopennsl                 3.2.2.2-8+0~20170515203732.42~1.gbp386641 amd64        shared library for broadcom opennsl sdk
ii  libsaibcm                  2.1.5.1-7+0~20170519212441.39~1.gbpc7b67f amd64        Switch Abstraction Interface sdk based on Broa
dcom opennsl
7. CAN NOT get the dump file in `syncd` so we got it under the host
#####
root@sonic:/home/admin# docker exec -it syncd bash
root@sonic:/# generate_dump
bash: generate_dump: command not found
root@sonic:/# exit
exit
root@sonic:/home/admin# generate_dump
/var/dump/sonic_dump_sonic_20010101_005626.tar.gz
#####
syncd core dump zip: sonic_dump_sonic_20010101_005626-n205-host.tar.gz (as attached)

**Comment by pollyhsu2git** [comment]
The following is the GREPed 'syncd` in syslog of last post (the Jenkins#205 test base)

root@sonic:/home/admin# cat /var/log/syslog | grep syncd
Jan  1 00:47:23.0 sonic INFO supervisord 2001-01-01 00:46:09,596 INFO waiting for lldp-syncd, lldpd-conf-reload, rsyslogd, lldpd to
die
Jan  1 00:47:23.0 sonic INFO supervisord 2001-01-01 00:46:09,598 INFO stopped: lldp-syncd (terminated by SIGTERM)
Jan  1 00:47:23.0 sonic INFO supervisord 2001-01-01 00:46:09,606 INFO waiting for fpmsyncd, rsyslogd to die
Jan  1 00:47:23.0 sonic INFO supervisord 2001-01-01 00:46:09,607 INFO stopped: fpmsyncd (terminated by SIGTERM)
Jan  1 00:47:23.947627 sonic INFO syncd.sh[1433]: syncd
Jan  1 00:47:25.187768 sonic INFO bgp.sh[1135]: 2001-01-01 00:47:25,187 INFO spawned: 'fpmsyncd' with pid 50
Jan  1 00:47:25.0 sonic INFO supervisord: fpmsyncd Waiting for connection...
Jan  1 00:47:25.0 sonic NOTICE fpmsyncd: :- loadRedisScript: lua script loaded, sha: e70c5f65367f8b9fed2deb3daa5ee4ba40f90c58
Jan  1 00:47:25.0 sonic INFO supervisord 2001-01-01 00:46:16,346 INFO waiting for syncd, rsyslogd to die
Jan  1 00:47:25.0 sonic INFO supervisord 2001-01-01 00:46:16,363 INFO stopped: syncd (exit status 0)
Jan  1 00:47:26.222735 sonic INFO bgp.sh[1135]: 2001-01-01 00:47:26,222 INFO success: fpmsyncd entered RUNNING state, process has st
ayed up for > than 1 seconds (startsecs)
Jan  1 00:47:26.0 sonic INFO supervisord: start.sh fpmsyncd: started
Jan  1 00:47:26.829759 sonic INFO lldp.sh[1179]: 2001-01-01 00:47:26,829 INFO spawned: 'lldp-syncd' with pid 28
Jan  1 00:47:26.0 sonic NOTICE syncd: :- main: syncd started
Jan  1 00:47:27.0 sonic NOTICE syncd: :- saiLoglevelNotify: Setting SAI loglevel SAI_API_ACL to SAI_LOG_NOTICE
Jan  1 00:47:27.0 sonic NOTICE syncd: :- saiLoglevelNotify: Setting SAI loglevel SAI_API_BUFFERS to SAI_LOG_NOTICE
Jan  1 00:47:27.0 sonic NOTICE syncd: :- saiLoglevelNotify: Setting SAI loglevel SAI_API_FDB to SAI_LOG_NOTICE
Jan  1 00:47:27.0 sonic NOTICE syncd: :- saiLoglevelNotify: Setting SAI loglevel SAI_API_HASH to SAI_LOG_NOTICE
Jan  1 00:47:27.0 sonic NOTICE syncd: :- saiLoglevelNotify: Setting SAI loglevel SAI_API_HOST_INTERFACE to SAI_LOG_NOTICE
Jan  1 00:47:27.0 sonic NOTICE syncd: :- saiLoglevelNotify: Setting SAI loglevel SAI_API_LAG to SAI_LOG_NOTICE
Jan  1 00:47:27.0 sonic NOTICE syncd: :- saiLoglevelNotify: Setting SAI loglevel SAI_API_MIRROR to SAI_LOG_NOTICE
Jan  1 00:47:27.0 sonic NOTICE syncd: :- saiLoglevelNotify: Setting SAI loglevel SAI_API_NEIGHBOR to SAI_LOG_NOTICE
Jan  1 00:47:27.0 sonic NOTICE syncd: :- saiLoglevelNotify: Setting SAI loglevel SAI_API_NEXT_HOP to SAI_LOG_NOTICE
Jan  1 00:47:27.0 sonic NOTICE syncd: :- saiLoglevelNotify: Setting SAI loglevel SAI_API_NEXT_HOP_GROUP to SAI_LOG_NOTICE
Jan  1 00:47:27.0 sonic NOTICE syncd: :- saiLoglevelNotify: Setting SAI loglevel SAI_API_POLICER to SAI_LOG_NOTICE
Jan  1 00:47:27.0 sonic NOTICE syncd: :- saiLoglevelNotify: Setting SAI loglevel SAI_API_PORT to SAI_LOG_NOTICE
Jan  1 00:47:27.0 sonic NOTICE syncd: :- saiLoglevelNotify: Setting SAI loglevel SAI_API_QOS_MAPS to SAI_LOG_NOTICE
Jan  1 00:47:27.0 sonic NOTICE syncd: :- saiLoglevelNotify: Setting SAI loglevel SAI_API_QUEUE to SAI_LOG_NOTICE
Jan  1 00:47:27.0 sonic NOTICE syncd: :- saiLoglevelNotify: Setting SAI loglevel SAI_API_ROUTE to SAI_LOG_NOTICE
Jan  1 00:47:27.0 sonic NOTICE syncd: :- saiLoglevelNotify: Setting SAI loglevel SAI_API_ROUTER_INTERFACE to SAI_LOG_NOTICE
Jan  1 00:47:27.0 sonic NOTICE syncd: :- saiLoglevelNotify: Setting SAI loglevel SAI_API_SAMPLEPACKET to SAI_LOG_NOTICE
Jan  1 00:47:27.0 sonic NOTICE syncd: :- saiLoglevelNotify: Setting SAI loglevel SAI_API_SCHEDULER to SAI_LOG_NOTICE
Jan  1 00:47:27.0 sonic NOTICE syncd: :- saiLoglevelNotify: Setting SAI loglevel SAI_API_SCHEDULER_GROUP to SAI_LOG_NOTICE
Jan  1 00:47:27.0 sonic NOTICE syncd: :- saiLoglevelNotify: Setting SAI loglevel SAI_API_STP to SAI_LOG_NOTICE
Jan  1 00:47:27.0 sonic NOTICE syncd: :- saiLoglevelNotify: Setting SAI loglevel SAI_API_SWITCH to SAI_LOG_NOTICE
Jan  1 00:47:27.0 sonic NOTICE syncd: :- saiLoglevelNotify: Setting SAI loglevel SAI_API_TUNNEL to SAI_LOG_NOTICE
Jan  1 00:47:27.0 sonic NOTICE syncd: :- saiLoglevelNotify: Setting SAI loglevel SAI_API_UDF to SAI_LOG_NOTICE
Jan  1 00:47:27.0 sonic NOTICE syncd: :- saiLoglevelNotify: Setting SAI loglevel SAI_API_VIRTUAL_ROUTER to SAI_LOG_NOTICE
Jan  1 00:47:27.0 sonic NOTICE syncd: :- saiLoglevelNotify: Setting SAI loglevel SAI_API_VLAN to SAI_LOG_NOTICE
Jan  1 00:47:27.0 sonic NOTICE syncd: :- saiLoglevelNotify: Setting SAI loglevel SAI_API_WRED to SAI_LOG_NOTICE
Jan  1 00:47:27.0 sonic ERR syncd: :- get_attr_name: object type 20 attr id 256 not found in map!
Jan  1 00:47:27.0 sonic NOTICE syncd: :- handleCmdLine: enable diag shell
Jan  1 00:47:27.0 sonic NOTICE syncd: :- handleCmdLine: profile map file: /usr/share/sonic/hwsku/sai.profile
Jan  1 00:47:27.0 sonic WARNING syncd: :- handleProfileMap: not found '=' in line
Jan  1 00:47:27.0 sonic NOTICE syncd: :- isVeryFirstRun: First Run: True
Jan  1 00:47:27.0 sonic NOTICE syncd: :- main: starting initializing ASIC
Jan  1 00:47:27.0 sonic INFO supervisord: syncd [6] daemon mode
Jan  1 00:47:27.0 sonic INFO supervisord: syncd Platform configuration file "/etc/bcm/th-as7712-32x100G.config.bcm" is used#015
Jan  1 00:47:27.0 sonic INFO supervisord: syncd Platform Boot flags: 0x0#015
Jan  1 00:47:27.0 sonic NOTICE syncd: :- loadRedisScript: lua script loaded, sha: e70c5f65367f8b9fed2deb3daa5ee4ba40f90c58
Jan  1 00:47:27.0 sonic INFO lldp-syncd [lldp_syncd] INFO: Starting SONiC LLDP sync daemon...
Jan  1 00:47:27.0 sonic INFO supervisord: syncd Defaulting the board ID to Broadcom reference platform.#015
Jan  1 00:47:27.0 sonic INFO supervisord: start.sh syncd: started
Jan  1 00:47:27.832061 sonic INFO lldp.sh[1179]: 2001-01-01 00:47:27,831 INFO success: lldp-syncd entered RUNNING state, process has
 stayed up for > than 1 seconds (startsecs)
Jan  1 00:47:27.0 sonic INFO supervisord: start.sh lldp-syncd: started
Jan  1 00:47:29.0 sonic INFO supervisord: syncd DMA pool size: 16777216#015
Jan  1 00:47:29.0 sonic INFO supervisord: fpmsyncd Connected!
Jan  1 00:47:30.0 sonic INFO supervisord: syncd PCI unit 0: Dev 0xb960, Rev 0x11, Chip BCM56960_B0, Driver BCM56960_A0#015
Jan  1 00:47:30.0 sonic INFO supervisord: syncd #015#015
Jan  1 00:47:30.0 sonic INFO supervisord: syncd Initializing platform#015#015
Jan  1 00:47:30.0 sonic INFO supervisord: syncd SOC unit 0 attached to PCI device BCM56960_B0#015
Jan  1 00:47:30.0 sonic INFO supervisord: syncd Boot flags: Cold boot#015
Jan  1 00:47:30.0 sonic INFO supervisord: syncd rc: unit 0 device BCM56960_B0#015
Jan  1 00:47:30.0 sonic INFO supervisord: syncd *** unit 0: configured for normal latency#015
Jan  1 00:47:31.0 sonic INFO supervisord: syncd rc: MMU initialized#015
Jan  1 00:47:31.0 sonic INFO supervisord: syncd *** unit 0: ports capable of limited speed range cut-thru#015
Jan  1 00:47:32.0 sonic INFO supervisord: syncd rc: L2 Table shadowing
Jan  1 00:47:32.0 sonic INFO supervisord: syncd  enabled#015
Jan  1 00:47:32.0 sonic INFO supervisord: syncd rc:
Jan  1 00:47:32.0 sonic INFO supervisord: syncd
Jan  1 00:47:32.0 sonic INFO supervisord: syncd Port
Jan  1 00:47:32.0 sonic INFO supervisord: syncd
Jan  1 00:47:32.0 sonic INFO supervisord: syncd modes
Jan  1 00:47:32.0 sonic INFO supervisord: syncd
Jan  1 00:47:32.0 sonic INFO supervisord: syncd initialized
Jan  1 00:47:32.0 sonic INFO supervisord: syncd #015
Jan  1 00:47:32.0 sonic INFO supervisord: syncd Common SDK init completed#015#015
Jan  1 00:47:33.0 sonic INFO supervisord 2001-01-01 00:47:26,829 INFO spawned: 'lldp-syncd' with pid 28
Jan  1 00:47:33.0 sonic INFO supervisord 2001-01-01 00:47:27,831 INFO success: lldp-syncd entered RUNNING state, process has stayed
up for > than 1 seconds (startsecs)
Jan  1 00:47:33.0 sonic INFO supervisord 2001-01-01 00:47:25,187 INFO spawned: 'fpmsyncd' with pid 50
Jan  1 00:47:33.0 sonic INFO supervisord 2001-01-01 00:47:26,222 INFO success: fpmsyncd entered RUNNING state, process has stayed up

 for > than 1 seconds (startsecs)
Jan  1 00:47:34.428690 sonic INFO kernel: [   41.965864] syncd[1640]: segfault at 0 ip 00007ff61f59f3ba sp 00007fffa0e3c440 error 6
in libsai.so.1.0[7ff61f548000+95000]
Jan  1 00:47:35.0 sonic INFO supervisord 2001-01-01 00:47:26,527 INFO spawned: 'syncd' with pid 17
Jan  1 00:47:35.0 sonic INFO supervisord 2001-01-01 00:47:27,708 INFO success: syncd entered RUNNING state, process has stayed up fo
r > than 1 seconds (startsecs)
Jan  1 00:47:35.0 sonic NOTICE dsserve: child /usr/bin/syncd exited status: 139
Jan  1 00:47:35.0 sonic INFO supervisord: syncd [5] child /usr/bin/syncd exited status: 139

**Comment by lguohan** [comment]
resolved in https://github.com/Azure/sonic-buildimage/commit/5f8e495cb0ba20e89809e7ef511cea3ce3dfa388
