### ISSUE TITLE
Access Denied when try to download the image

### ISSUE THREAD

**Issue by hahalone** [Azure/SONiC#865]
Hello there,

It said Access Denied, my username missing the Overall/Read permission when trying to download a OS image for mellanox SN2700 at
https://github.com/Azure/SONiC/wiki/Supported-Devices-and-Platforms

Could you help me see it.

Thanks

**Comment by sourcequench** [comment]
Same issue for me, denied. In my case I'm trying to fetch the qemu image at:

https://sonic-jenkins.westus2.cloudapp.azure.com/job/vs/job/buildimage-vs201911/lastSuccessfulBuild/artifact/target/

**Comment by ym** [comment]
Artifacts download has been moved to but I'm not sure why the document isn't updated yet.

https://sonic-build.azurewebsites.net/ui/sonic/pipelines

**Comment by hahalone** [comment]
> Artifacts download has been moved to but I'm not sure why the document isn't updated yet.
> 
> https://sonic-build.azurewebsites.net/ui/sonic/pipelines

Oh. Thanks. You saved my ass. I guess 
target/sonic-mellanox.bin at https://sonic-build.azurewebsites.net/ui/sonic/pipelines/139/builds/36971/artifacts/73496?branchName=master&artifactName=sonic-buildimage.mellanox is the file I suppose to use to install SONiC to the switch. Is that right:p
<html>
<body>


target/sonic-mellanox.bin
--



</body>
</html>

**Comment by hahalone** [comment]
> > Artifacts download has been moved to but I'm not sure why the document isn't updated yet.
> > https://sonic-build.azurewebsites.net/ui/sonic/pipelines
> 
> Oh. Thanks. You saved my ass. I guess
> target/sonic-mellanox.bin
> at
> https://sonic-build.azurewebsites.net/ui/sonic/pipelines/139/builds/36971/artifacts/73496?branchName=master&artifactName=sonic-buildimage.mellanox is the file I suppose to use to install SONiC to the switch. Is that right:p

Yes I confirmed the bin file found from the build history, artifacts is working for OS installation. I will close the issue

**Comment by caopeirui** [comment]
@hahalone Could you tell me your steps of modifing your p4 origin ONL system to SONiC system? I want to do it, but lack of manual in spite of reading https://github.com/Azure/SONiC/wiki/Quick-Start

**Comment by hahalone** [comment]
> p4 origin ONL system

Sorry, I am not a frequent user here. I think you mean how did I install SONiC to my switch. Mine comes with ONIE and i use a console cable to connect it and installed the OS with the guide you mentioned. Hope you sorted it out already.
